name = "fhmm"
version = "1.4.3"
license = "GPL-3.0-only"
author = "Lennart Oelschlaeger, Timo Adam, Rouven Michels; Fortran translation"
maintainer = "Fortran community"
copyright = "Copyright (C) fHMM authors"
description = "Modern Fortran implementation of numerical algorithms from the fHMM R package"
categories = ["finance", "time-series", "statistics"]
gams = ["L"]
keywords = ["estimation", "hidden-markov-models", "finance", "time-series", "statistics", "statistical-computing"]

[build]
auto-executables = true
auto-examples = true
auto-tests = true
module-naming = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
