name = "gradient"
version = "0.1.0"
license = "MIT"
author = "Brendan Matthew Galdo; Fortran translation by OpenAI"
maintainer = ""
copyright = "Copyright (c) 2022 Brendan Galdo"
description = "Modern Fortran translation of the computational code in the R package graDiEnt"
categories = ["optimization", "probability", "numerical"]
keywords = ["gradient-methods", "numerical-differentiation", "optimization", "probability", "numerical", "statistical-computing"]

[library]
source-dir = "src"

[build]
auto-executables = false
auto-examples = true
auto-tests = true

[install]
library = true

[extra.r-fpm-index]
gams = ["G", "H", "L"]
