#!/usr/bin/env sh
RUGARCH_SOURCES="
vendor/rugarch-modern-fortran/src/rugarch_kinds.f90
vendor/rugarch-modern-fortran/src/rugarch_math.f90
vendor/rugarch-modern-fortran/src/rugarch_rng.f90
vendor/rugarch-modern-fortran/src/rugarch_gh.f90
vendor/rugarch-modern-fortran/src/rugarch_distributions.f90
vendor/rugarch-modern-fortran/src/rugarch_optimizer.f90
vendor/rugarch-modern-fortran/src/rugarch_linalg.f90
vendor/rugarch-modern-fortran/src/rugarch_resampling.f90
vendor/rugarch-modern-fortran/src/rugarch_types.f90
vendor/rugarch-modern-fortran/src/rugarch_models.f90
vendor/rugarch-modern-fortran/src/rugarch_fit.f90
vendor/rugarch-modern-fortran/src/rugarch_risk.f90
vendor/rugarch-modern-fortran/src/rugarch_arfima.f90
vendor/rugarch-modern-fortran/src/rugarch_backtests.f90
vendor/rugarch-modern-fortran/src/rugarch_inference.f90
vendor/rugarch-modern-fortran/src/rugarch_evaluation.f90
vendor/rugarch-modern-fortran/src/rugarch_workflows.f90
vendor/rugarch-modern-fortran/src/rugarch_complete.f90
vendor/rugarch-modern-fortran/src/rugarch.f90"
QUARKS_SOURCES="
src/quarks_kinds.f90
src/quarks_types.f90
src/quarks_rng.f90
src/quarks_stats.f90
src/quarks_smoothing.f90
src/quarks_risk.f90
src/quarks_backtests.f90
src/quarks_portfolio.f90
src/quarks_rollcast.f90
src/quarks.f90"
