program test_classical_tests
   use stats_test_assertions, only: assert_close, assert_integer
   use r_stats, only: chisq_test, chisq_test_result_t, cor_test, cor_test_result_t, dp, &
                      prop_test, prop_test_result_t
   implicit none

   real(dp), parameter :: tolerance = 3.0e-8_dp
   integer, parameter :: contingency(2, 2) = reshape([10, 20, 20, 10], [2, 2])
   real(dp), parameter :: cor_x(6) = [1.0_dp, 2.0_dp, 4.0_dp, 7.0_dp, 11.0_dp, 16.0_dp]
   real(dp), parameter :: cor_y(6) = [2.0_dp, 1.0_dp, 5.0_dp, 8.0_dp, 9.0_dp, 15.0_dp]
   type(chisq_test_result_t) :: chi_result
   type(cor_test_result_t) :: correlation_result
   type(prop_test_result_t) :: proportion_result

   ! Reference values generated by R 4.6.0 stats functions.
   chi_result = chisq_test([10, 20, 30], p=[0.2_dp, 0.3_dp, 0.5_dp])
   call assert_close(chi_result%statistic, 0.55555555555555558_dp, "goodness-of-fit statistic", &
      allowed_error=tolerance)
   call assert_close(chi_result%p_value, 0.75746512839696645_dp, "goodness-of-fit p-value", &
      allowed_error=tolerance)
   call assert_integer(chi_result%parameter, 2, "goodness-of-fit degrees of freedom")
   call assert_integer(chi_result%method, 1, "goodness-of-fit method")

   chi_result = chisq_test(contingency)
   call assert_close(chi_result%statistic, 5.4000000000000004_dp, "corrected independence statistic", &
      allowed_error=tolerance)
   call assert_close(chi_result%p_value, 0.020136751550346353_dp, "corrected independence p-value", &
      allowed_error=tolerance)
   call assert_integer(chi_result%parameter, 1, "independence degrees of freedom")
   call assert_integer(chi_result%method, 2, "independence method")

   chi_result = chisq_test(contingency, correct=.false.)
   call assert_close(chi_result%statistic, 6.666666666666667_dp, "uncorrected independence statistic", &
      allowed_error=tolerance)
   call assert_close(chi_result%p_value, 0.0098232745075192644_dp, "uncorrected independence p-value", &
      allowed_error=tolerance)

   proportion_result = prop_test(60, 100, p=0.5_dp)
   call assert_proportion(proportion_result, 3.61_dp, 0.057433119632003746_dp, &
                          0.49700356057171358_dp, 0.69521992889954343_dp, &
                          "corrected one-proportion")
   call assert_close(proportion_result%estimate, 0.6_dp, "one-proportion estimate", &
      allowed_error=tolerance)
   call assert_close(proportion_result%null_value, 0.5_dp, "one-proportion null value", &
      allowed_error=tolerance)
   call assert_integer(proportion_result%parameter, 1, "one-proportion degrees of freedom")

   proportion_result = prop_test(60, 100, p=0.5_dp, correct=.false.)
   call assert_proportion(proportion_result, 4.0_dp, 0.045500263896358473_dp, &
                          0.5020025867910618_dp, 0.69059871356754099_dp, &
                          "uncorrected one-proportion")

   proportion_result = prop_test([30, 45], [50, 80])
   call assert_proportion(proportion_result, 0.056924242424242225_dp, &
                          0.8114250569497139_dp, -0.15269249027342841_dp, &
                          0.22769249027342836_dp, "corrected two-proportion")
   call assert_close(proportion_result%estimate, 0.6_dp, "first proportion estimate", &
      allowed_error=tolerance)
   call assert_close(proportion_result%estimate2, 0.5625_dp, "second proportion estimate", &
      allowed_error=tolerance)

   proportion_result = prop_test([30, 45], [50, 80], correct=.false.)
   call assert_proportion(proportion_result, 0.17727272727272694_dp, &
                          0.67372756807050627_dp, -0.13644249027342839_dp, &
                          0.21144249027342835_dp, "uncorrected two-proportion")

   correlation_result = cor_test(cor_x, cor_y)
   call assert_close(correlation_result%statistic, 9.0967667087937993_dp, "Pearson statistic", &
      allowed_error=tolerance)
   call assert_close(correlation_result%p_value, 0.00080984272214592223_dp, "Pearson p-value", &
      allowed_error=tolerance)
   call assert_close(correlation_result%estimate, 0.97667349144486804_dp, "Pearson estimate", &
      allowed_error=tolerance)
   call assert_close(correlation_result%conf_low, 0.79622183244642908_dp, "Pearson lower limit", &
      allowed_error=tolerance)
   call assert_close(correlation_result%conf_high, 0.99754795105568872_dp, "Pearson upper limit", &
      allowed_error=tolerance)
   call assert_integer(correlation_result%parameter, 4, "Pearson degrees of freedom")
   call assert_integer(correlation_result%method, 1, "Pearson method")

   correlation_result = cor_test(cor_x, cor_y, method="spearman")
   call assert_close(correlation_result%statistic, 2.0000000000000004_dp, "Spearman statistic", &
      allowed_error=tolerance)
   call assert_close(correlation_result%p_value, 0.0048046647230320675_dp, "Spearman p-value", &
      allowed_error=tolerance)
   call assert_close(correlation_result%estimate, 0.94285714285714284_dp, "Spearman estimate", &
      allowed_error=tolerance)
   call assert_integer(correlation_result%method, 2, "Spearman method")

   print *, "test_classical_tests: PASS"

contains

   subroutine assert_proportion(actual, statistic, p_value, conf_low, conf_high, label)
      !! Checks the principal numerical fields of a proportion-test result.
      type(prop_test_result_t), intent(in) :: actual !! Computed proportion-test result.
      real(dp), intent(in) :: statistic !! Expected chi-square statistic.
      real(dp), intent(in) :: p_value !! Expected two-sided p-value.
      real(dp), intent(in) :: conf_low !! Expected lower confidence limit.
      real(dp), intent(in) :: conf_high !! Expected upper confidence limit.
      character(len=*), intent(in) :: label !! Case description used in failure messages.

      call assert_close(actual%statistic, statistic, label//" statistic", allowed_error=tolerance)
      call assert_close(actual%p_value, p_value, label//" p-value", allowed_error=tolerance)
      call assert_close(actual%conf_low, conf_low, label//" lower confidence limit", &
      allowed_error=tolerance)
      call assert_close(actual%conf_high, conf_high, label//" upper confidence limit", &
      allowed_error=tolerance)
   end subroutine assert_proportion


end program test_classical_tests
