program test_arima
   use stats_test_assertions, only: assert_close, assert_integer, assert_matrix_close, &
                                      assert_vector_close
   use, intrinsic :: ieee_arithmetic, only: ieee_is_nan, ieee_quiet_nan, ieee_value
   use r_stats, only: arima_css, arima_fit_t, arima_forecast_t, arima_ml, dp
   use r_stats, only: predict_arima, predict_arima_interval
   implicit none

   real(dp), parameter :: parameter_tolerance = 2.0e-5_dp
   real(dp), parameter :: covariance_tolerance = 1.0e-4_dp
   real(dp) :: future_regressor(5, 1), regressor(24, 1), seasonal_missing(80)
   real(dp) :: seasonal_x(80), x(24), x_missing(24)
   real(dp), allocatable :: prediction(:)
   integer :: i
   type(arima_fit_t) :: fit
   type(arima_forecast_t) :: interval

   x = [2.0_dp, 1.0_dp, 4.0_dp, 3.0_dp, 7.0_dp, 5.0_dp, 8.0_dp, 6.0_dp, &
        5.0_dp, 4.0_dp, 7.0_dp, 9.0_dp, 6.0_dp, 3.0_dp, 2.0_dp, 1.0_dp, &
        4.0_dp, 6.0_dp, 5.0_dp, 7.0_dp, 8.0_dp, 6.0_dp, 4.0_dp, 3.0_dp]
   do i = 1, size(x)
      regressor(i, 1) = sin(0.4_dp*real(i, dp))
   end do
   do i = 1, size(future_regressor, 1)
      future_regressor(i, 1) = sin(0.4_dp*real(size(x) + i, dp))
   end do
   x_missing = x
   x_missing([4, 11]) = ieee_value(0.0_dp, ieee_quiet_nan)

   ! Reference values generated by R 4.6.0 stats::arima(method="CSS").
   fit = arima_css(x, [1, 0, 1])
   call assert_integer(fit%status, 0, "ARMA(1,1) convergence")
   call assert_vector_close(fit%ar, [0.476641124871067_dp], "ARMA(1,1) AR", &
      allowed_error=parameter_tolerance)
   call assert_vector_close(fit%ma, [0.0442269716041431_dp], "ARMA(1,1) MA", &
      allowed_error=parameter_tolerance)
   call assert_close(fit%mean, 4.98078277226626_dp, "ARMA(1,1) mean", &
      allowed_error=parameter_tolerance)
   call assert_close(fit%variance, 3.42990771152746_dp, "ARMA(1,1) variance", &
      allowed_error=parameter_tolerance)
   call assert_close(fit%log_likelihood, -48.8449250515800_dp, "ARMA(1,1) likelihood", &
      allowed_error=parameter_tolerance)
   call assert_integer(fit%covariance_status, 0, "ARMA(1,1) covariance status")
   call assert_matrix_close(fit%coef_covariance, reshape([ &
      0.0477106344150853_dp, -0.0308561323486270_dp, 0.0177896644760579_dp, &
     -0.0308561323486270_dp, 0.0557692021388076_dp, -0.0242106312243893_dp, &
      0.0177896644760579_dp, -0.0242106312243893_dp, 0.577939667643482_dp], [3, 3]), &
      "ARMA(1,1) covariance", allowed_error=covariance_tolerance)
   call assert_integer(fit%n_conditioned, 1, "ARMA(1,1) conditioned count")
   call assert_integer(fit%n_used, 24, "ARMA(1,1) observation count")
   call assert_close(fit%residuals(1), 0.0_dp, "ARMA(1,1) leading residual", &
      allowed_error=parameter_tolerance)
   prediction = predict_arima(fit, 5)
   call assert_vector_close(prediction, &
      [3.97255633376863_dp, 4.50022058849600_dp, 4.75172707242351_dp, &
       4.87160540583508_dp, 4.92874434952004_dp], "ARMA(1,1) forecasts", &
      allowed_error=parameter_tolerance)

   fit = arima_css(x, [1, 0, 1], fixed_values=[0.25_dp, 0.0_dp, 0.0_dp], &
                   fixed_mask=[.true., .false., .false.])
   call assert_integer(fit%status, 0, "fixed CSS ARMA(1,1) convergence")
   call assert_vector_close(fit%ar, [0.25_dp], "fixed CSS AR coefficient", &
      allowed_error=parameter_tolerance)
   call assert_vector_close(fit%ma, [0.191737513947998_dp], "fixed CSS MA coefficient", &
      allowed_error=parameter_tolerance)
   call assert_close(fit%mean, 4.90973629593967_dp, "fixed CSS mean", &
      allowed_error=parameter_tolerance)
   call assert_close(fit%variance, 3.56204384451441_dp, "fixed CSS variance", &
      allowed_error=parameter_tolerance)
   call assert_matrix_close(fit%coef_covariance, reshape([ &
      0.0_dp, 0.0_dp, 0.0_dp, &
      0.0_dp, 0.0268471107363677_dp, -0.00997749985221816_dp, &
      0.0_dp, -0.00997749985221816_dp, 0.372671902068732_dp], [3, 3]), &
      "fixed CSS covariance", allowed_error=covariance_tolerance)
   if (.not. all(fit%fixed .eqv. [.true., .false., .false.])) then
      error stop "fixed CSS mask"
   end if

   fit = arima_css(x, [1, 0, 0], xreg=regressor)
   call assert_integer(fit%status, 0, "CSS regression convergence")
   call assert_vector_close(fit%ar, [0.506353599933680_dp], "CSS regression AR", &
      allowed_error=parameter_tolerance)
   call assert_close(fit%mean, 4.97068884386302_dp, "CSS regression mean", &
      allowed_error=parameter_tolerance)
   call assert_vector_close(fit%regression, [0.182239189024906_dp], &
                            "CSS regression coefficient", allowed_error=parameter_tolerance)
   call assert_close(fit%variance, 3.42984548409688_dp, "CSS regression variance", &
      allowed_error=parameter_tolerance)
   prediction = predict_arima(fit, 5, future_regressor)
   call assert_vector_close(prediction, &
      [3.88976792158488_dp, 4.32269911066377_dp, 4.54020161836434_dp, &
       4.66478384519936_dp, 4.75619717364880_dp], "CSS regression forecasts", &
      allowed_error=parameter_tolerance)

   fit = arima_css(x, [0, 0, 2])
   call assert_integer(fit%status, 0, "MA(2) convergence")
   call assert_vector_close(fit%ma, &
      [0.618570976321015_dp, 0.404572929659803_dp], "MA(2) coefficients", &
      allowed_error=parameter_tolerance)
   call assert_close(fit%mean, 4.53803524078966_dp, "MA(2) mean", allowed_error=parameter_tolerance)
   call assert_close(fit%variance, 3.26741320287291_dp, "MA(2) variance", &
      allowed_error=parameter_tolerance)

   fit = arima_css(x, [0, 1, 0])
   call assert_integer(fit%status, 0, "ARIMA(0,1,0) status")
   call assert_integer(fit%n_conditioned, 1, "ARIMA(0,1,0) conditioned count")
   if (fit%include_mean) error stop "differenced model must omit mean"
   prediction = predict_arima(fit, 3)
   call assert_vector_close(prediction, [3.0_dp, 3.0_dp, 3.0_dp], "random-walk forecasts", &
      allowed_error=parameter_tolerance)

   fit = arima_css(x, [1, 1, 0])
   call assert_integer(fit%status, 0, "ARIMA(1,1,0) convergence")
   call assert_vector_close(fit%ar, [-0.113207553123137_dp], "ARIMA(1,1,0) AR", &
      allowed_error=parameter_tolerance)
   call assert_close(fit%variance, 4.75643224699828_dp, "ARIMA(1,1,0) variance", &
      allowed_error=parameter_tolerance)
   call assert_close(fit%log_likelihood, -50.5698116452583_dp, "ARIMA(1,1,0) likelihood", &
      allowed_error=parameter_tolerance)
   call assert_integer(fit%n_conditioned, 2, "ARIMA(1,1,0) conditioned count")
   call assert_integer(fit%n_used, 23, "ARIMA(1,1,0) observation count")
   prediction = predict_arima(fit, 4)
   call assert_vector_close(prediction, &
      [3.11320755312314_dp, 3.10039160303901_dp, 3.10184246538898_dp, &
       3.10167821681242_dp], "ARIMA(1,1,0) forecasts", allowed_error=parameter_tolerance)

   fit = arima_ml(x, [1, 0, 0])
   call assert_integer(fit%status, 0, "exact AR(1) convergence")
   call assert_vector_close(fit%ar, [0.519678833399872_dp], "exact AR(1) coefficient", &
      allowed_error=parameter_tolerance)
   call assert_close(fit%mean, 4.64035571145233_dp, "exact AR(1) mean", &
      allowed_error=parameter_tolerance)
   call assert_close(fit%variance, 3.53466775510348_dp, "exact AR(1) variance", &
      allowed_error=parameter_tolerance)
   call assert_close(fit%log_likelihood, -49.3633571307119_dp, "exact AR(1) likelihood", &
      allowed_error=parameter_tolerance)
   call assert_close(fit%residuals(1), -2.25581878758007_dp, "exact AR(1) first residual", &
      allowed_error=parameter_tolerance)
   if (trim(fit%method) /= "ML") error stop "exact AR(1) method"
   prediction = predict_arima(fit, 5)
   call assert_vector_close(prediction, &
      [3.78789756896397_dp, 4.19735125844175_dp, 4.41013567412084_dp, &
       4.52071523102663_dp, 4.57818108615730_dp], "exact AR(1) forecasts", &
      allowed_error=parameter_tolerance)

   fit = arima_ml(x, [1, 0, 1])
   call assert_integer(fit%status, 0, "exact ARMA(1,1) convergence")
   call assert_vector_close(fit%ar, [0.414269782586358_dp], "exact ARMA(1,1) AR", &
      allowed_error=parameter_tolerance)
   call assert_vector_close(fit%ma, [0.146634416165983_dp], "exact ARMA(1,1) MA", &
      allowed_error=parameter_tolerance)
   call assert_close(fit%mean, 4.68495948097986_dp, "exact ARMA(1,1) mean", &
      allowed_error=parameter_tolerance)
   call assert_close(fit%variance, 3.48357855341158_dp, "exact ARMA(1,1) variance", &
      allowed_error=parameter_tolerance)
   call assert_close(fit%log_likelihood, -49.1952278576397_dp, "exact ARMA(1,1) likelihood", &
      allowed_error=parameter_tolerance)
   call assert_matrix_close(fit%coef_covariance, reshape([ &
      0.0768982308262860_dp, -0.0508671908657578_dp, -0.0332200374517988_dp, &
     -0.0508671908657578_dp, 0.0621023726429090_dp, 0.0197228778868451_dp, &
     -0.0332200374517988_dp, 0.0197228778868451_dp, 0.534585126818861_dp], [3, 3]), &
      "exact ARMA(1,1) covariance", allowed_error=covariance_tolerance)
   call assert_close(fit%residuals(24), -1.22852069569264_dp, "exact ARMA(1,1) final residual", &
      allowed_error=parameter_tolerance)
   prediction = predict_arima(fit, 5)
   call assert_vector_close(prediction, &
      [3.80678826816679_dp, 4.32115968357419_dp, 4.53424821800365_dp, &
       4.62252435883339_dp, 4.65909449650249_dp], "exact ARMA(1,1) forecasts", &
      allowed_error=parameter_tolerance)
   interval = predict_arima_interval(fit, 5, confidence_level=0.9_dp)
   call assert_integer(interval%status, 0, "exact ARMA(1,1) interval status")
   call assert_vector_close(interval%standard_error, &
      [1.86643471715771_dp, 2.13999052916526_dp, 2.18349515895720_dp, &
       2.19087455009388_dp, 2.19213849971760_dp], "exact ARMA(1,1) standard errors", &
      allowed_error=parameter_tolerance)
   call assert_vector_close(interval%lower, &
      [0.736776354181789_dp, 0.801188500034916_dp, 0.942718286361926_dp, &
       1.01885640891579_dp, 1.05334753446204_dp], "exact ARMA(1,1) lower intervals", &
      allowed_error=parameter_tolerance)
   call assert_vector_close(interval%upper, &
      [6.87680018215179_dp, 7.84113086711346_dp, 8.12577814964537_dp, &
       8.22619230875098_dp, 8.26484145854293_dp], "exact ARMA(1,1) upper intervals", &
      allowed_error=parameter_tolerance)

   fit = arima_ml(x, [1, 0, 1], fixed_values=[0.25_dp, 0.0_dp, 0.0_dp], &
                  fixed_mask=[.true., .false., .false.])
   call assert_integer(fit%status, 0, "fixed exact ARMA(1,1) convergence")
   call assert_vector_close(fit%ar, [0.25_dp], "fixed exact AR coefficient", &
      allowed_error=parameter_tolerance)
   call assert_vector_close(fit%ma, [0.255000082285337_dp], "fixed exact MA coefficient", &
      allowed_error=parameter_tolerance)
   call assert_close(fit%mean, 4.74046841978850_dp, "fixed exact mean", &
      allowed_error=parameter_tolerance)
   call assert_close(fit%variance, 3.53864924354173_dp, "fixed exact variance", &
      allowed_error=parameter_tolerance)
   call assert_matrix_close(fit%coef_covariance, reshape([ &
      0.0_dp, 0.0_dp, 0.0_dp, &
      0.0_dp, 0.0245036461122000_dp, -0.00117765600194705_dp, &
      0.0_dp, -0.00117765600194705_dp, 0.395237989623327_dp], [3, 3]), &
      "fixed exact covariance", allowed_error=covariance_tolerance)

   fit = arima_ml(x, [1, 0, 1], fixed_values=[0.25_dp, -0.1_dp, 4.5_dp], &
                  fixed_mask=[.true., .true., .true.])
   call assert_integer(fit%status, 0, "fully fixed exact ARMA(1,1) status")
   call assert_integer(fit%iterations, 0, "fully fixed exact ARMA(1,1) iterations")
   call assert_vector_close(fit%ar, [0.25_dp], "fully fixed exact AR coefficient", &
      allowed_error=parameter_tolerance)
   call assert_vector_close(fit%ma, [-0.1_dp], "fully fixed exact MA coefficient", &
      allowed_error=parameter_tolerance)
   call assert_close(fit%mean, 4.5_dp, "fully fixed exact mean", allowed_error=parameter_tolerance)
   call assert_close(fit%variance, 4.26422723080179_dp, "fully fixed exact variance", &
      allowed_error=parameter_tolerance)
   call assert_integer(fit%covariance_status, 0, "fully fixed covariance status")
   if (any(fit%coef_covariance /= 0.0_dp)) error stop "fully fixed covariance"

   fit = arima_ml(x, [1, 0, 0], xreg=regressor)
   call assert_integer(fit%status, 0, "exact regression convergence")
   call assert_vector_close(fit%ar, [0.522347424671734_dp], "exact regression AR", &
      allowed_error=parameter_tolerance)
   call assert_close(fit%mean, 4.62356316934603_dp, "exact regression mean", &
      allowed_error=parameter_tolerance)
   call assert_vector_close(fit%regression, [0.077316704280341_dp], &
                            "exact regression coefficient", allowed_error=parameter_tolerance)
   call assert_close(fit%variance, 3.53328019372048_dp, "exact regression variance", &
      allowed_error=parameter_tolerance)
   call assert_matrix_close(fit%coef_covariance, reshape([ &
      0.0329117651423792_dp, -0.0311988931739737_dp, 0.0399775287500399_dp, &
     -0.0311988931739737_dp, 0.658971276575208_dp, -0.235290124403885_dp, &
      0.0399775287500399_dp, -0.235290124403885_dp, 1.07348796303094_dp], [3, 3]), &
      "exact regression covariance", allowed_error=covariance_tolerance)
   if (size(predict_arima(fit, 5)) /= 0) error stop "missing future regressors"
   prediction = predict_arima(fit, 5, future_regressor)
   call assert_vector_close(prediction, &
      [3.74047760269659_dp, 4.12025181878692_dp, 4.31824977507469_dp, &
       4.42799297770283_dp, 4.49733443760606_dp], "exact regression forecasts", &
      allowed_error=parameter_tolerance)
   interval = predict_arima_interval(fit, 5, confidence_level=0.9_dp, &
                                     new_xreg=future_regressor)
   call assert_vector_close(interval%standard_error, &
      [1.87970215558755_dp, 2.12068962872026_dp, 2.18182513888446_dp, &
       2.19821054377379_dp, 2.20266008402554_dp], "exact regression standard errors", &
      allowed_error=parameter_tolerance)

   fit = arima_ml(x_missing, [1, 0, 1])
   call assert_integer(fit%status, 0, "missing-data exact convergence")
   call assert_integer(fit%n_used, 22, "missing-data observation count")
   call assert_vector_close(fit%ar, [0.213432781406765_dp], "missing-data exact AR", &
      allowed_error=parameter_tolerance)
   call assert_vector_close(fit%ma, [0.524182301367281_dp], "missing-data exact MA", &
      allowed_error=parameter_tolerance)
   call assert_close(fit%mean, 4.86731908616231_dp, "missing-data exact mean", &
      allowed_error=parameter_tolerance)
   call assert_close(fit%variance, 3.06267745839820_dp, "missing-data exact variance", &
      allowed_error=parameter_tolerance)
   call assert_close(fit%log_likelihood, -44.3740051123590_dp, &
                     "missing-data exact likelihood", allowed_error=parameter_tolerance)
   if (.not. ieee_is_nan(fit%residuals(4)) .or. &
       .not. ieee_is_nan(fit%residuals(11))) error stop "missing-data residual markers"
   call assert_close(fit%residuals(5), 1.65538849682542_dp, &
                     "missing-data resumed residual", allowed_error=parameter_tolerance)
   call assert_matrix_close(fit%coef_covariance, reshape([ &
      0.132369250000485_dp, -0.120783714670255_dp, -0.0397925837243847_dp, &
     -0.120783714670255_dp, 0.168591006977559_dp, 0.0451068218682845_dp, &
     -0.0397925837243847_dp, 0.0451068218682845_dp, 0.474040926148791_dp], [3, 3]), &
      "missing-data exact covariance", allowed_error=covariance_tolerance)
   prediction = predict_arima(fit, 5)
   call assert_vector_close(prediction, &
      [3.84944147663843_dp, 4.65007063682996_dp, 4.82095114536500_dp, &
       4.85742264758983_dp, 4.86520686175176_dp], "missing-data forecasts", &
      allowed_error=parameter_tolerance)
   interval = predict_arima_interval(fit, 5, confidence_level=0.9_dp)
   call assert_vector_close(interval%standard_error, &
      [1.75005071550496_dp, 2.17462796659922_dp, 2.19201140763575_dp, &
       2.19280000333484_dp, 2.19283591991648_dp], "missing-data standard errors", &
      allowed_error=parameter_tolerance)

   fit = arima_css(x_missing, [1, 0, 1])
   call assert_integer(fit%status, 1, "CSS missing-data rejection")
   fit = arima_ml(x_missing, [0, 1, 0])
   call assert_integer(fit%status, 0, "missing-data random-walk status")
   call assert_integer(fit%n_used, 21, "missing-data random-walk observation count")
   call assert_close(fit%variance, 4.47619047619089_dp, &
                     "missing-data random-walk variance", allowed_error=parameter_tolerance)
   call assert_close(fit%log_likelihood, -46.2279659955938_dp, &
                     "missing-data random-walk likelihood", allowed_error=parameter_tolerance)
   if (.not. ieee_is_nan(fit%residuals(4)) .or. &
       .not. ieee_is_nan(fit%residuals(11))) error stop "missing-data random-walk markers"
   call assert_close(fit%residuals(5), 2.12132034355964_dp, &
                     "missing-data random-walk resumed residual", allowed_error=parameter_tolerance)
   prediction = predict_arima(fit, 5)
   call assert_vector_close(prediction, [3.0_dp, 3.0_dp, 3.0_dp, 3.0_dp, 3.0_dp], &
                            "missing-data random-walk forecasts", allowed_error=parameter_tolerance)
   interval = predict_arima_interval(fit, 5, confidence_level=0.9_dp)
   call assert_vector_close(interval%standard_error, &
      [2.11570094204991_dp, 2.99205296617252_dp, 3.66450152525179_dp, &
       4.23140188409982_dp, 4.73085112648395_dp], &
      "missing-data random-walk standard errors", allowed_error=parameter_tolerance)

   fit = arima_ml(x_missing, [1, 1, 0])
   call assert_integer(fit%status, 0, "missing-data ARIMA(1,1,0) status")
   call assert_vector_close(fit%ar, [0.0176861556857873_dp], &
                            "missing-data ARIMA(1,1,0) AR", allowed_error=parameter_tolerance)
   call assert_close(fit%variance, 4.46724230492826_dp, &
                     "missing-data ARIMA(1,1,0) variance", allowed_error=parameter_tolerance)
   call assert_close(fit%log_likelihood, -46.2249501789474_dp, &
                     "missing-data ARIMA(1,1,0) likelihood", allowed_error=parameter_tolerance)
   call assert_matrix_close(fit%coef_covariance, &
                            reshape([0.0516786499162593_dp], [1, 1]), &
                            "missing-data ARIMA(1,1,0) covariance", &
      allowed_error=covariance_tolerance)
   prediction = predict_arima(fit, 5)
   call assert_vector_close(prediction, &
      [2.98231384431421_dp, 2.98200104421127_dp, 2.98199551197995_dp, &
       2.98199541413605_dp, 2.98199541240556_dp], &
      "missing-data ARIMA(1,1,0) forecasts", allowed_error=parameter_tolerance)
   interval = predict_arima_interval(fit, 5, confidence_level=0.9_dp)
   call assert_vector_close(interval%standard_error, &
      [2.11358517806315_dp, 3.01560916723165_dp, 3.70451070540882_dp, &
       4.28403440706347_dp, 4.79400698009953_dp], &
      "missing-data ARIMA(1,1,0) standard errors", allowed_error=parameter_tolerance)

   fit = arima_ml(x, [0, 0, 2])
   call assert_integer(fit%status, 0, "exact MA(2) convergence")
   call assert_vector_close(fit%ma, &
      [0.631969201129137_dp, 0.422608650008787_dp], "exact MA(2) coefficients", &
      allowed_error=parameter_tolerance)
   call assert_close(fit%mean, 4.69803206362637_dp, "exact MA(2) mean", &
      allowed_error=parameter_tolerance)
   call assert_close(fit%variance, 3.11401166703476_dp, "exact MA(2) variance", &
      allowed_error=parameter_tolerance)
   call assert_close(fit%log_likelihood, -47.9921230452300_dp, "exact MA(2) likelihood", &
      allowed_error=parameter_tolerance)
   prediction = predict_arima(fit, 5)
   call assert_vector_close(prediction, &
      [3.91159631792737_dp, 4.43684807606386_dp, 4.69803206362637_dp, &
       4.69803206362637_dp, 4.69803206362637_dp], "exact MA(2) forecasts", &
      allowed_error=parameter_tolerance)

   fit = arima_ml(x, [0, 1, 0])
   call assert_integer(fit%status, 0, "exact random-walk status")
   call assert_close(fit%variance, 4.65217391304385_dp, "exact random-walk variance", &
      allowed_error=parameter_tolerance)
   call assert_close(fit%log_likelihood, -50.3149343768308_dp, "exact random-walk likelihood", &
      allowed_error=parameter_tolerance)
   call assert_close(fit%residuals(2), -1.0_dp, "exact random-walk first difference", &
      allowed_error=parameter_tolerance)
   prediction = predict_arima(fit, 5)
   call assert_vector_close(prediction, &
      [3.0_dp, 3.0_dp, 3.0_dp, 3.0_dp, 3.0_dp], "exact random-walk forecasts", &
      allowed_error=parameter_tolerance)
   interval = predict_arima_interval(fit, 5, confidence_level=0.9_dp)
   call assert_vector_close(interval%standard_error, &
      [2.15688987040225_dp, 3.05030290726802_dp, 3.73584284186736_dp, &
       4.31377974080451_dp, 4.82295237020015_dp], "exact random-walk standard errors", &
      allowed_error=parameter_tolerance)

   do i = 1, size(x)
      regressor(i, 1) = real(i, dp)/10.0_dp
   end do
   do i = 1, size(future_regressor, 1)
      future_regressor(i, 1) = real(size(x) + i, dp)/10.0_dp
   end do
   fit = arima_ml(x, [0, 1, 0], xreg=regressor)
   call assert_integer(fit%status, 0, "integrated regression convergence")
   call assert_vector_close(fit%regression, [0.434782608680340_dp], &
                            "integrated regression coefficient", allowed_error=parameter_tolerance)
   call assert_close(fit%variance, 4.65028355387564_dp, "integrated regression variance", &
      allowed_error=parameter_tolerance)
   prediction = predict_arima(fit, 5, future_regressor)
   call assert_vector_close(prediction, &
      [3.04347826086803_dp, 3.08695652173607_dp, 3.13043478260410_dp, &
       3.17391304347214_dp, 3.21739130434017_dp], "integrated regression forecasts", &
      allowed_error=parameter_tolerance)
   interval = predict_arima_interval(fit, 5, confidence_level=0.9_dp, &
                                     new_xreg=future_regressor)
   call assert_vector_close(interval%standard_error, &
      [2.15645161176309_dp, 3.04968311595669_dp, 3.73508375563747_dp, &
       4.31290322352619_dp, 4.82197239409126_dp], &
      "integrated regression standard errors", allowed_error=parameter_tolerance)

   fit = arima_ml(x, [1, 1, 0])
   call assert_integer(fit%status, 0, "exact ARIMA(1,1,0) convergence")
   call assert_vector_close(fit%ar, [-0.109440905177489_dp], "exact ARIMA(1,1,0) AR", &
      allowed_error=parameter_tolerance)
   call assert_close(fit%variance, 4.59265372092088_dp, "exact ARIMA(1,1,0) variance", &
      allowed_error=parameter_tolerance)
   call assert_close(fit%log_likelihood, -50.1728781781833_dp, "exact ARIMA(1,1,0) likelihood", &
      allowed_error=parameter_tolerance)
   prediction = predict_arima(fit, 5)
   call assert_vector_close(prediction, &
      [3.10944090517749_dp, 3.09746359345142_dp, 3.09877440128832_dp, &
       3.09863094529213_dp, 3.09864664524621_dp], "exact ARIMA(1,1,0) forecasts", &
      allowed_error=parameter_tolerance)
   interval = predict_arima_interval(fit, 5, confidence_level=0.9_dp)
   call assert_vector_close(interval%standard_error, &
      [2.14304776449823_dp, 2.86968059657141_dp, 3.46065220630769_dp, &
       3.96311769399143_dp, 4.40881816907787_dp], "exact ARIMA(1,1,0) standard errors", &
      allowed_error=parameter_tolerance)

   fit = arima_css(x, [-1, 0, 0])
   call assert_integer(fit%status, 1, "invalid order status")
   if (size(predict_arima(fit, 2)) /= 0) error stop "invalid fit forecast"

   seasonal_x = 10.0_dp
   do i = 1, size(seasonal_x)
      seasonal_x(i) = 10.0_dp + sin(1.7_dp*real(i, dp)) + 0.3_dp*cos(0.23_dp*real(i, dp))
      if (i > 1) seasonal_x(i) = seasonal_x(i) + 0.3_dp*(seasonal_x(i - 1) - 10.0_dp)
      if (i > 4) seasonal_x(i) = seasonal_x(i) + 0.45_dp*(seasonal_x(i - 4) - 10.0_dp)
      if (i > 5) seasonal_x(i) = seasonal_x(i) - 0.135_dp*(seasonal_x(i - 5) - 10.0_dp)
   end do

   fit = arima_css(seasonal_x, [1, 0, 0], seasonal_order=[1, 0, 0], period=4)
   call assert_integer(fit%status, 0, "multiplicative seasonal AR convergence")
   call assert_vector_close(fit%ar, [0.166451651096799_dp], "seasonal model AR", &
      allowed_error=parameter_tolerance)
   call assert_vector_close(fit%seasonal_ar, [0.857938551589763_dp], "seasonal model SAR", &
      allowed_error=parameter_tolerance)
   call assert_close(fit%mean, 9.78014659277179_dp, "seasonal AR mean", &
      allowed_error=parameter_tolerance)
   call assert_close(fit%variance, 0.323633741365940_dp, "seasonal AR variance", &
      allowed_error=parameter_tolerance)
   call assert_close(fit%log_likelihood, -68.3893694368447_dp, "seasonal AR likelihood", &
      allowed_error=parameter_tolerance)
   call assert_integer(fit%n_conditioned, 5, "seasonal AR conditioned count")
   prediction = predict_arima(fit, 6)
   call assert_vector_close(prediction, &
      [8.65958054747426_dp, 10.0400009070280_dp, 11.3264781905856_dp, &
       9.86717848140070_dp, 8.81874199069895_dp, 10.0030810007099_dp], &
      "multiplicative seasonal AR forecasts", allowed_error=parameter_tolerance)

   fit = arima_css(seasonal_x, [1, 0, 0], seasonal_order=[1, 0, 0], period=4, &
                   fixed_values=[0.0_dp, 0.5_dp, 0.0_dp], &
                   fixed_mask=[.false., .true., .false.])
   call assert_integer(fit%status, 0, "fixed seasonal CSS convergence")
   call assert_vector_close(fit%ar, [0.057059787151265_dp], "fixed seasonal CSS AR", &
      allowed_error=parameter_tolerance)
   call assert_vector_close(fit%seasonal_ar, [0.5_dp], "fixed seasonal CSS SAR", &
      allowed_error=parameter_tolerance)
   call assert_close(fit%mean, 9.92112985285925_dp, "fixed seasonal CSS mean", &
      allowed_error=parameter_tolerance)
   call assert_close(fit%variance, 0.464495386081215_dp, "fixed seasonal CSS variance", &
      allowed_error=parameter_tolerance)

   fit = arima_css(seasonal_x, [0, 0, 1], seasonal_order=[0, 0, 1], period=4)
   call assert_integer(fit%status, 0, "multiplicative seasonal MA convergence")
   call assert_vector_close(fit%ma, [0.925261952273232_dp], "seasonal model MA", &
      allowed_error=parameter_tolerance)
   call assert_vector_close(fit%seasonal_ma, [0.929010638785577_dp], "seasonal model SMA", &
      allowed_error=parameter_tolerance)
   call assert_close(fit%mean, 10.2835257663068_dp, "seasonal MA mean", &
      allowed_error=parameter_tolerance)
   call assert_close(fit%variance, 0.233023145050196_dp, "seasonal MA variance", &
      allowed_error=parameter_tolerance)
   call assert_close(fit%log_likelihood, -55.2503828415560_dp, "seasonal MA likelihood", &
      allowed_error=parameter_tolerance)
   prediction = predict_arima(fit, 6)
   call assert_integer(size(prediction), 6, "seasonal MA forecast size")
   call assert_close(prediction(6), fit%mean, "seasonal MA forecast after residual memory", &
      allowed_error=parameter_tolerance)

   fit = arima_css(seasonal_x, [0, 0, 0], seasonal_order=[0, 1, 0], period=4)
   call assert_integer(fit%status, 0, "seasonal random-walk status")
   call assert_integer(fit%n_conditioned, 4, "seasonal random-walk conditioned count")
   prediction = predict_arima(fit, 8)
   call assert_vector_close(prediction, &
      [seasonal_x(77), seasonal_x(78), seasonal_x(79), seasonal_x(80), &
       seasonal_x(77), seasonal_x(78), seasonal_x(79), seasonal_x(80)], &
      "seasonal random-walk forecasts", allowed_error=parameter_tolerance)

   fit = arima_ml(seasonal_x, [1, 0, 0], seasonal_order=[1, 0, 0], period=4)
   call assert_integer(fit%status, 0, "exact seasonal AR convergence")
   call assert_vector_close(fit%ar, [0.166658170544621_dp], "exact seasonal AR", &
      allowed_error=parameter_tolerance)
   call assert_vector_close(fit%seasonal_ar, [0.845018170076775_dp], "exact seasonal SAR", &
      allowed_error=parameter_tolerance)
   call assert_close(fit%mean, 10.0653767701734_dp, "exact seasonal mean", &
      allowed_error=parameter_tolerance)
   call assert_close(fit%variance, 0.315912895527411_dp, "exact seasonal variance", &
      allowed_error=parameter_tolerance)
   call assert_close(fit%log_likelihood, -69.9421852589446_dp, "exact seasonal likelihood", &
      allowed_error=parameter_tolerance)
   prediction = predict_arima(fit, 6)
   call assert_vector_close(prediction, &
      [8.71350518418788_dp, 10.0790930185316_dp, 11.3471950229135_dp, &
       9.91003955446041_dp, 8.92298768588130_dp, 10.0769617444547_dp], &
      "exact seasonal AR forecasts", allowed_error=parameter_tolerance)
   interval = predict_arima_interval(fit, 8, confidence_level=0.9_dp)
   call assert_vector_close(interval%standard_error, &
      [0.562061291610988_dp, 0.569813442348580_dp, 0.570027253147469_dp, &
       0.570033190586151_dp, 0.742246126136272_dp, 0.746462465694822_dp, &
       0.746579234424778_dp, 0.746582477409251_dp], &
      "exact seasonal AR standard errors", allowed_error=parameter_tolerance)

   fit = arima_ml(seasonal_x, [0, 0, 1], seasonal_order=[0, 0, 1], period=4)
   call assert_integer(fit%status, 0, "exact seasonal MA convergence")
   call assert_vector_close(fit%ma, [0.999999529891612_dp], "exact seasonal MA", &
      allowed_error=parameter_tolerance)
   call assert_vector_close(fit%seasonal_ma, [0.999999453382571_dp], "exact seasonal SMA", &
      allowed_error=parameter_tolerance)
   call assert_close(fit%mean, 10.0049046844559_dp, "exact seasonal MA mean", &
      allowed_error=parameter_tolerance)
   call assert_close(fit%variance, 0.173360930943630_dp, "exact seasonal MA variance", &
      allowed_error=parameter_tolerance)
   call assert_close(fit%log_likelihood, -51.0595022047271_dp, "exact seasonal MA likelihood", &
      allowed_error=parameter_tolerance)
   prediction = predict_arima(fit, 6)
   call assert_vector_close(prediction, &
      [8.93559738412796_dp, 10.3446960144526_dp, 10.8666760302772_dp, &
       9.89521458859263_dp, 9.58227897232300_dp, 10.0049046844559_dp], &
      "exact seasonal MA forecasts", allowed_error=parameter_tolerance)

   fit = arima_ml(seasonal_x, [0, 0, 0], seasonal_order=[0, 1, 0], period=4)
   call assert_integer(fit%status, 0, "exact seasonal random-walk status")
   call assert_close(fit%variance, 0.357049948551152_dp, "exact seasonal random-walk variance", &
      allowed_error=parameter_tolerance)
   call assert_close(fit%log_likelihood, -68.7039039104497_dp, &
                     "exact seasonal random-walk likelihood", allowed_error=parameter_tolerance)
   call assert_close(fit%residuals(5), 0.365977794180252_dp, &
                     "exact first seasonal difference", allowed_error=parameter_tolerance)
   prediction = predict_arima(fit, 8)
   call assert_vector_close(prediction, &
      [seasonal_x(77), seasonal_x(78), seasonal_x(79), seasonal_x(80), &
       seasonal_x(77), seasonal_x(78), seasonal_x(79), seasonal_x(80)], &
      "exact seasonal random-walk forecasts", allowed_error=parameter_tolerance)
   interval = predict_arima_interval(fit, 8, confidence_level=0.9_dp)
   call assert_vector_close(interval%standard_error, &
      [0.597536566706299_dp, 0.597536566706299_dp, 0.597536566706299_dp, &
       0.597536566706299_dp, 0.845044316649904_dp, 0.845044316649904_dp, &
       0.845044316649904_dp, 0.845044316649904_dp], &
      "exact seasonal random-walk standard errors", allowed_error=parameter_tolerance)

   seasonal_missing = seasonal_x
   seasonal_missing([13, 34]) = ieee_value(0.0_dp, ieee_quiet_nan)
   fit = arima_ml(seasonal_missing, [0, 0, 0], seasonal_order=[0, 1, 0], period=4)
   call assert_integer(fit%status, 0, "missing-data seasonal random-walk status")
   call assert_integer(fit%n_used, 74, "missing-data seasonal observation count")
   call assert_close(fit%variance, 0.365293103154981_dp, &
                     "missing-data seasonal random-walk variance", &
      allowed_error=parameter_tolerance)
   call assert_close(fit%log_likelihood, -68.4335553013233_dp, &
                     "missing-data seasonal random-walk likelihood", &
      allowed_error=parameter_tolerance)
   if (.not. ieee_is_nan(fit%residuals(13)) .or. &
       .not. ieee_is_nan(fit%residuals(34))) error stop "missing-data seasonal markers"
   prediction = predict_arima(fit, 8)
   call assert_vector_close(prediction, &
      [8.51623221494447_dp, 10.0900530830005_dp, 11.5836961605400_dp, &
       9.88178424168053_dp, 8.51623221494447_dp, 10.0900530830005_dp, &
       11.5836961605400_dp, 9.88178424168053_dp], &
      "missing-data seasonal random-walk forecasts", allowed_error=parameter_tolerance)
   interval = predict_arima_interval(fit, 8, confidence_level=0.9_dp)
   call assert_vector_close(interval%standard_error, &
      [0.604394823898237_dp, 0.604394823898237_dp, 0.604394823898237_dp, &
       0.604394823898237_dp, 0.854743356984986_dp, 0.854743356984986_dp, &
       0.854743356984986_dp, 0.854743356984986_dp], &
      "missing-data seasonal random-walk standard errors", allowed_error=parameter_tolerance)

   fit = arima_ml(seasonal_missing, [0, 1, 0], seasonal_order=[0, 1, 0], period=4)
   call assert_integer(fit%status, 0, "missing-data doubly differenced status")
   call assert_integer(fit%n_used, 73, "missing-data doubly differenced observation count")
   call assert_close(fit%variance, 0.598427706826446_dp, &
                     "missing-data doubly differenced variance", allowed_error=parameter_tolerance)
   call assert_close(fit%log_likelihood, -86.2278986416905_dp, &
                     "missing-data doubly differenced likelihood", &
      allowed_error=parameter_tolerance)
   prediction = predict_arima(fit, 8)
   call assert_vector_close(prediction, &
      [8.24587433272621_dp, 9.81969520078226_dp, 11.3133382783217_dp, &
       9.61142635946226_dp, 7.97551645050794_dp, 9.54933731856399_dp, &
       11.0429803961035_dp, 9.34106847724400_dp], &
      "missing-data doubly differenced forecasts", allowed_error=parameter_tolerance)
   interval = predict_arima_interval(fit, 8, confidence_level=0.9_dp)
   call assert_vector_close(interval%standard_error, &
      [0.773581092598860_dp, 1.09400887274870_dp, 1.33988175615587_dp, &
       1.54716218519772_dp, 2.18801774549741_dp, 2.67976351231174_dp, &
       3.09432437039544_dp, 3.45955981831922_dp], &
      "missing-data doubly differenced standard errors", allowed_error=parameter_tolerance)

   fit = arima_ml(seasonal_x, [0, 1, 0], seasonal_order=[0, 1, 0], period=4)
   call assert_integer(fit%status, 0, "exact doubly differenced status")
   call assert_close(fit%variance, 0.583974251815336_dp, "exact doubly differenced variance", &
      allowed_error=parameter_tolerance)
   call assert_close(fit%log_likelihood, -86.2492004974432_dp, &
                     "exact doubly differenced likelihood", allowed_error=parameter_tolerance)
   prediction = predict_arima(fit, 8)
   call assert_vector_close(prediction, &
      [8.24587433272621_dp, 9.81969520078226_dp, 11.3133382783217_dp, &
       9.61142635946227_dp, 7.97551645050795_dp, 9.54933731856400_dp, &
       11.0429803961035_dp, 9.34106847724401_dp], &
      "exact doubly differenced forecasts", allowed_error=parameter_tolerance)

   fit = arima_css(seasonal_x, [0, 0, 0], seasonal_order=[1, 0, 0])
   call assert_integer(fit%status, 1, "missing seasonal period status")

   fit = arima_ml(x, [1, 0, 0], fixed_values=[0.25_dp, 4.5_dp])
   call assert_integer(fit%status, 1, "fixed values without mask status")

   print *, "test_arima: PASS"

end program test_arima
