program test_generalized_linear_models
   use stats_test_assertions, only: assert_close, assert_equal, assert_true, assert_vector_close
   use r_stats, only: dp, glm_binomial_fit, glm_fit_t, glm_gamma_fit, glm_gaussian_fit, &
                      glm_inverse_link, glm_link_cauchit, glm_link_cloglog, glm_link_log, &
                      glm_link_probit, glm_link_sqrt, glm_link_value, glm_pearson_resid, &
                      glm_poisson_fit, glm_predict_response, glm_quasibinomial_fit, &
                      glm_quasipoisson_fit
   implicit none

   real(dp), parameter :: default_tolerance = 2.0e-8_dp
   real(dp) :: gamma_predictor(8, 1), gaussian_predictors(6, 2)
   real(dp) :: no_predictors(4, 0), new_no_predictors(2, 0), one_predictor(6, 1)
   real(dp) :: offset4(4), poisson_offset(6), probabilities(3), weighted_binomial_predictor(5, 1)
   real(dp), allocatable :: actual(:)
   type(glm_fit_t) :: fit

   fit = glm_binomial_fit([0, 1, 1, 0], no_predictors)
   call assert_equal(fit%family, 1, "binomial family code")
   call assert_equal(fit%convergence, 0, "binomial convergence")
   call assert_equal(fit%df, 3, "binomial residual degrees of freedom")
   call assert_vector_close(fit%coef, [0.0_dp], "binomial intercept")
   call assert_vector_close(fit%fitted, spread(0.5_dp, 1, 4), "binomial fitted probabilities")
   call assert_vector_close(fit%se, [1.0_dp], "binomial standard error")
   actual = glm_pearson_resid(fit)
   call assert_vector_close(actual, [-1.0_dp, 1.0_dp, 1.0_dp, -1.0_dp], "binomial Pearson residuals")
   actual = glm_predict_response(fit, new_no_predictors)
   call assert_vector_close(actual, [0.5_dp, 0.5_dp], "binomial prediction")

   fit = glm_poisson_fit([2, 2, 2, 2], no_predictors)
   call assert_equal(fit%family, 2, "Poisson family code")
   call assert_equal(fit%convergence, 0, "Poisson convergence")
   call assert_vector_close(fit%coef, [log(2.0_dp)], "Poisson intercept")
   call assert_vector_close(fit%fitted, spread(2.0_dp, 1, 4), "Poisson fitted means")
   call assert_vector_close(fit%se, [1.0_dp/sqrt(8.0_dp)], "Poisson standard error")

   offset4 = log(2.0_dp)
   fit = glm_poisson_fit([2, 2, 2, 2], no_predictors, offset=offset4)
   call assert_vector_close(fit%coef, [0.0_dp], "Poisson offset intercept")
   call assert_vector_close(fit%offset, offset4, "Poisson stored offset")

   ! Reference values generated by R 4.6.0 glm(..., family=binomial()).
   one_predictor(:, 1) = [-2.0_dp, -1.0_dp, 0.0_dp, 1.0_dp, 2.0_dp, 3.0_dp]
   fit = glm_binomial_fit([0, 0, 1, 0, 1, 1], one_predictor)
   call assert_vector_close(fit%coef, [-0.60701379292530211_dp, 1.21402758585060533_dp], &
                            "R binomial coefficients")
   call assert_vector_close(fit%fitted, &
      [0.045866483853065972_dp, 0.139308962682062415_dp, 0.352740692689461788_dp, &
       0.647259307310538490_dp, 0.860691037317937724_dp, 0.954133516146934091_dp], &
      "R binomial fitted probabilities")
   call assert_vector_close(fit%se, [1.21810469899521778_dp, 0.91258483831201076_dp], &
                            "R binomial standard errors", 2.0e-6_dp)

   fit = glm_binomial_fit([0, 0, 1, 0, 1, 1], one_predictor, link=glm_link_probit)
   call assert_vector_close(fit%coef, [-0.37988947117514160_dp, 0.75977894235028276_dp], &
                            "R probit coefficients", 5.0e-6_dp)
   call assert_vector_close(fit%fitted, &
      [0.028752841053399949_dp, 0.127212235663818618_dp, 0.352013731639399807_dp, &
       0.647986268360600026_dp, 0.872787764336181215_dp, 0.971247158946600075_dp], &
      "R probit fitted probabilities", 5.0e-6_dp)

   fit = glm_binomial_fit([0, 0, 1, 0, 1, 1], one_predictor, link=glm_link_cloglog)
   call assert_vector_close(fit%coef, [-0.98377368612083549_dp, 0.88609651615561447_dp], &
                            "R cloglog coefficients", 5.0e-6_dp)
   call assert_vector_close(fit%fitted, &
      [0.061570510999161963_dp, 0.142851132710363343_dp, 0.311952540472101914_dp, &
       0.596242829358931692_dp, 0.889187574827148719_dp, 0.995185923568817410_dp], &
      "R cloglog fitted probabilities", 5.0e-6_dp)

   probabilities = [0.2_dp, 0.5_dp, 0.8_dp]
   call assert_vector_close(glm_inverse_link(glm_link_value(probabilities, glm_link_probit), &
                                             glm_link_probit), &
                            probabilities, "probit link round trip", 2.0e-8_dp)
   call assert_vector_close(glm_inverse_link(glm_link_value(probabilities, glm_link_cauchit), &
                                             glm_link_cauchit), &
                            probabilities, "cauchit link round trip", 2.0e-12_dp)

   ! Reference values generated by R 4.6.0 glm(..., family=poisson()).
   one_predictor(:, 1) = [0.0_dp, 1.0_dp, 2.0_dp, 3.0_dp, 4.0_dp, 5.0_dp]
   poisson_offset = log([1.0_dp, 1.5_dp, 2.0_dp, 1.0_dp, 2.5_dp, 3.0_dp])
   fit = glm_poisson_fit([1, 2, 1, 4, 6, 8], one_predictor, poisson_offset)
   call assert_vector_close(fit%coef, [-0.069503819431542671_dp, 0.227516721358669127_dp], &
                            "R Poisson coefficients")
   call assert_vector_close(fit%fitted, &
      [0.93285657039594194_dp, 1.75677195765906458_dp, 2.94078573911465035_dp, &
       1.84604653559532816_dp, 5.79417902884942482_dp, 8.72936016838558437_dp], &
      "R Poisson fitted means")
   call assert_vector_close(fit%se, [0.55591515264589120_dp, 0.14118702258804272_dp], &
                            "R Poisson standard errors", 2.0e-6_dp)
   actual = glm_pearson_resid(fit)
   call assert_vector_close(actual, &
      [0.069517810181530276_dp, 0.183508400200335875_dp, -1.131738005756799836_dp, &
       1.585312901291412224_dp, 0.085505424630790680_dp, -0.246860063150121378_dp], &
      "R Poisson Pearson residuals")

   fit = glm_quasipoisson_fit([1.0_dp, 2.0_dp, 1.0_dp, 4.0_dp, 6.0_dp, 8.0_dp], one_predictor)
   call assert_vector_close(fit%coef, [-0.041252227501218944_dp, 0.432701422774609601_dp], &
                            "R quasi-Poisson coefficients", 2.0e-7_dp)
   call assert_close(fit%dispersion, 0.26204884953361052_dp, "R quasi-Poisson dispersion", 1.0e-6_dp)
   call assert_vector_close(fit%se, [0.293336279003740041_dp, 0.074876266445324732_dp], &
                            "R quasi-Poisson standard errors", 1.0e-6_dp)

   fit = glm_poisson_fit([1, 2, 1, 4, 6, 8], one_predictor, link=glm_link_sqrt)
   call assert_vector_close(fit%coef, [0.87275521569491288_dp, 0.37317202878992223_dp], &
                            "R square-root Poisson coefficients", 5.0e-6_dp)
   call assert_vector_close(fit%fitted, &
      [0.7617016665226739_dp, 1.5523346985495738_dp, 2.6214824567188475_dp, &
       3.9691449410304940_dp, 5.5953221514845133_dp, 7.5000140880809063_dp], &
      "R square-root Poisson fitted values", 2.0e-5_dp)

   ! R 4.6.0 weighted Gaussian identity fit with an exactly aliased column.
   gaussian_predictors(:, 1) = [0.0_dp, 1.0_dp, 2.0_dp, 3.0_dp, 4.0_dp, 5.0_dp]
   gaussian_predictors(:, 2) = 2.0_dp*gaussian_predictors(:, 1)
   fit = glm_gaussian_fit([1.2_dp, 2.0_dp, 2.9_dp, 4.1_dp, 5.2_dp, 5.8_dp], &
                          gaussian_predictors, weights=[1.0_dp, 2.0_dp, 1.0_dp, &
                                                        3.0_dp, 2.0_dp, 1.0_dp])
   call assert_equal(fit%rank, 2, "Gaussian numerical rank")
   call assert_true(fit%aliased(3), "Gaussian aliased predictor")
   call assert_vector_close(fit%coef(:2), [1.09017857142857211_dp, 0.98839285714285707_dp], &
                            "R Gaussian coefficients")
   call assert_vector_close(fit%fitted, &
      [1.0901785714285721_dp, 2.0785714285714292_dp, 3.0669642857142865_dp, &
       4.0553571428571429_dp, 5.0437500000000002_dp, 6.0321428571428575_dp], &
      "R Gaussian fitted values")
   call assert_close(fit%dispersion, 0.040245535714285831_dp, "R Gaussian dispersion")
   call assert_close(fit%deviance, 0.1609821428571433_dp, "R Gaussian deviance")
   call assert_vector_close(fit%se(:2), [0.127161634598551593_dp, 0.042387211532850529_dp], &
                            "R Gaussian standard errors")

   ! R 4.6.0 Gamma fit using the log link.
   gamma_predictor(:, 1) = [-1.5_dp, -0.5_dp, 0.0_dp, 0.5_dp, 1.0_dp, 1.5_dp, 2.0_dp, 2.5_dp]
   fit = glm_gamma_fit([1.1_dp, 1.5_dp, 1.9_dp, 2.2_dp, 3.2_dp, 3.8_dp, 5.4_dp, 6.8_dp], &
                       gamma_predictor, link=glm_link_log)
   call assert_vector_close(fit%coef, [0.68450275419021589_dp, 0.46885580992235942_dp], &
                            "R Gamma coefficients", 5.0e-7_dp)
   call assert_vector_close(fit%fitted, &
      [0.98139430262937444_dp, 1.56842957684141204_dp, 1.98278565851088806_dp, &
       2.50660853738412603_dp, 3.16881773514829268_dp, 4.00597288680324848_dp, &
       5.06429214650042070_dp, 6.40220382658957554_dp], "R Gamma fitted values", 5.0e-6_dp)
   call assert_close(fit%dispersion, 0.0073683549159861564_dp, "R Gamma dispersion", 2.0e-9_dp)
   call assert_close(fit%deviance, 0.044338022543487482_dp, "R Gamma deviance", 2.0e-9_dp)
   call assert_vector_close(fit%se, [0.034646191280910427_dp, 0.024309375921094212_dp], &
                            "R Gamma standard errors", 2.0e-8_dp)

   fit = glm_gamma_fit([1.1_dp, 1.5_dp, 1.9_dp, 2.2_dp, 3.2_dp, 3.8_dp, 5.4_dp, 6.8_dp], &
                       gamma_predictor)
   call assert_vector_close(fit%coef, [0.5268542756509984_dp, -0.1594781282305332_dp], &
                            "R inverse-Gamma coefficients", 2.0e-7_dp)
   call assert_vector_close(fit%fitted, &
      [1.3053612381817352_dp, 1.6485509062551262_dp, 1.8980580517532428_dp, &
       2.2365600055637644_dp, 2.7220057889482172_dp, 3.4766031851982921_dp, &
       4.8100506387529238_dp, 7.8028101853467833_dp], "R inverse-Gamma fitted values", 2.0e-6_dp)
   call assert_close(fit%dispersion, 0.017364607351741682_dp, &
                     "R inverse-Gamma dispersion", 2.0e-7_dp)
   call assert_close(fit%deviance, 0.10440614362454594_dp, &
                     "R inverse-Gamma deviance", 2.0e-7_dp)

   ! R 4.6.0 prior-weighted binomial-proportion fit.
   weighted_binomial_predictor(:, 1) = [-2.0_dp, -1.0_dp, 0.0_dp, 1.0_dp, 2.0_dp]
   fit = glm_binomial_fit([0.1_dp, 0.2_dp, 0.45_dp, 0.7_dp, 0.9_dp], &
                          weighted_binomial_predictor, &
                          weights=[10.0_dp, 15.0_dp, 20.0_dp, 15.0_dp, 10.0_dp])
   call assert_vector_close(fit%coef, [-0.20230597456259825_dp, 1.10768317582732245_dp], &
                            "R weighted-binomial coefficients", 2.0e-8_dp)
   call assert_vector_close(fit%fitted, &
      [0.081834982106364029_dp, 0.212488659660564072_dp, 0.449595301602565833_dp, &
       0.712053264461162350_dp, 0.882161528505914783_dp], &
      "R weighted-binomial fitted values", 2.0e-8_dp)
   call assert_close(fit%deviance, 0.098054659948187073_dp, "R weighted-binomial deviance", 2.0e-8_dp)
   call assert_vector_close(fit%se, [0.28602491681377185_dp, 0.28123388834765811_dp], &
                            "R weighted-binomial standard errors", 2.0e-8_dp)

   fit = glm_quasibinomial_fit([0.1_dp, 0.2_dp, 0.45_dp, 0.7_dp, 0.9_dp], &
                               weighted_binomial_predictor, &
                               weights=[10.0_dp, 15.0_dp, 20.0_dp, 15.0_dp, 10.0_dp])
   call assert_vector_close(fit%coef, [-0.20230597456259825_dp, 1.10768317582732245_dp], &
                            "R quasi-binomial coefficients", 2.0e-8_dp)
   call assert_close(fit%dispersion, 0.033049555905947513_dp, &
                     "R quasi-binomial dispersion", 2.0e-8_dp)
   call assert_vector_close(fit%se, [0.051998005072020195_dp, 0.051127018287874471_dp], &
                            "R quasi-binomial standard errors", 2.0e-8_dp)

   print *, "test_generalized_linear_models: PASS"

end program test_generalized_linear_models
