program test_smoothing
   use stats_test_assertions, only: assert_close, assert_integer, assert_vector_close, &
                                      assert_vector_close_tolerance
   use, intrinsic :: ieee_arithmetic, only: ieee_is_nan
   use r_stats, only: dp, ksmooth, loess_fit, loess_fit_t, lowess, predict_loess
   use r_stats, only: predict_smooth_spline, runmed, smooth_spline, smooth_spline_fit_t
   use r_stats, only: smooth_xy_t
   implicit none

   real(dp), parameter :: tolerance = 2.0e-10_dp
   real(dp) :: x(9), x_large(64), x_points(5), y(9), y_large(64)
   real(dp), allocatable :: prediction(:), values(:)
   integer :: i
   type(loess_fit_t) :: loess_model
   type(smooth_spline_fit_t) :: spline_model
   type(smooth_xy_t) :: smoothed

   x = [1.0_dp, 4.0_dp, 2.0_dp, 8.0_dp, 5.0_dp, 3.0_dp, 9.0_dp, 7.0_dp, 6.0_dp]
   y = [1.0_dp, 2.5_dp, 1.2_dp, 4.8_dp, 3.7_dp, 3.1_dp, 5.9_dp, 5.2_dp, 4.5_dp]
   x_points = [1.0_dp, 3.0_dp, 5.0_dp, 7.0_dp, 9.0_dp]

   ! Reference values generated by R 4.6.0 stats functions.
   values = runmed(y, 3)
   call assert_vector_close(values, [1.0_dp, 1.2_dp, 2.5_dp, 3.7_dp, 3.7_dp, &
                                     3.7_dp, 5.2_dp, 5.2_dp, 5.2_dp], "running median k=3", &
      allowed_error=tolerance)
   values = runmed(y, 5, endrule="median")
   call assert_vector_close(values, [2.5_dp, 2.5_dp, 2.5_dp, 3.1_dp, 3.7_dp, &
                                     4.8_dp, 4.5_dp, 4.5_dp, 4.5_dp], "running median endpoints", &
      allowed_error=tolerance)
   values = runmed(y, 5, endrule="keep")
   call assert_vector_close(values, [1.0_dp, 2.5_dp, 2.5_dp, 3.1_dp, 3.7_dp, &
                                     4.8_dp, 4.5_dp, 5.2_dp, 4.5_dp], "running median keep", &
      allowed_error=tolerance)
   values = runmed(y, 5, endrule="constant")
   call assert_vector_close(values, [2.5_dp, 2.5_dp, 2.5_dp, 3.1_dp, 3.7_dp, &
                                     4.8_dp, 4.5_dp, 4.5_dp, 4.5_dp], "running median constant", &
      allowed_error=tolerance)

   smoothed = ksmooth(x, y, kernel="normal", bandwidth=2.0_dp, x_points=x_points)
   call assert_vector_close(smoothed%x, x_points, "normal kernel x", allowed_error=tolerance)
   call assert_vector_close(smoothed%y, &
      [1.0949532504131287_dp, 2.5370203927927166_dp, 3.6260416927847077_dp, &
       4.9503095165206350_dp, 5.5772076223186140_dp], "normal kernel y", allowed_error=tolerance)
   smoothed = ksmooth(x, y, kernel="box", bandwidth=4.0_dp, x_points=x_points)
   call assert_vector_close(smoothed%y, &
      [1.7666666666666668_dp, 2.2999999999999998_dp, 3.7999999999999998_dp, &
       4.8200000000000003_dp, 5.2999999999999998_dp], "box kernel y", allowed_error=tolerance)

   smoothed = lowess(x, y, f=2.0_dp/3.0_dp, iter=3, delta=0.0_dp)
   call assert_vector_close(smoothed%x, [1.0_dp, 2.0_dp, 3.0_dp, 4.0_dp, 5.0_dp, &
                                         6.0_dp, 7.0_dp, 8.0_dp, 9.0_dp], "LOWESS x", &
      allowed_error=tolerance)
   call assert_vector_close(smoothed%y, &
      [0.91494249042334452_dp, 1.60300459980155097_dp, 2.25900363002536109_dp, &
       2.99406091050010970_dp, 3.67277490070332124_dp, 4.31385315243793066_dp, &
       4.84348721958616402_dp, 5.29245627781193306_dp, 5.70925323560630549_dp], "LOWESS y", &
      allowed_error=tolerance)

   loess_model = loess_fit(x, y, span=0.75_dp, degree=0)
   call assert_integer(loess_model%status, 0, "constant LOESS status")
   call assert_vector_close(loess_model%fitted_values, &
      [1.87024939154858_dp, 3.03153180750660_dp, 1.98908212081452_dp, &
       5.06976784180588_dp, 3.68749434743921_dp, 2.30895511502049_dp, &
       5.14045313887022_dp, 4.83793269441162_dp, 4.30426968914562_dp], &
      "constant LOESS fitted values", allowed_error=tolerance)
   prediction = predict_loess(loess_model, [0.5_dp, 2.5_dp, 5.5_dp, 9.5_dp])
   call assert_vector_close(prediction, &
      [1.82096395265561_dp, 2.09015063796404_dp, 4.01737598215615_dp, &
       5.16770279171306_dp], "constant LOESS predictions", allowed_error=tolerance)

   loess_model = loess_fit(x, y, span=0.75_dp, degree=1)
   call assert_vector_close(loess_model%fitted_values, &
      [0.926874149970581_dp, 3.03153180750660_dp, 1.63894755317002_dp, &
       5.28151075009470_dp, 3.68749434743921_dp, 2.30895511502049_dp, &
       5.69320398348196_dp, 4.83793269441162_dp, 4.30426968914562_dp], &
      "linear LOESS fitted values", allowed_error=tolerance)
   prediction = predict_loess(loess_model, [0.5_dp, 2.5_dp, 5.5_dp, 9.5_dp])
   call assert_vector_close(prediction, &
      [0.561051702170193_dp, 1.97578661872098_dp, 4.01737598215615_dp, &
       5.90225644450485_dp], "linear LOESS predictions", allowed_error=tolerance)

   loess_model = loess_fit(x, y, span=0.75_dp, degree=2)
   call assert_vector_close(loess_model%fitted_values, &
      [0.845334027560766_dp, 3.00273629833343_dp, 1.71654511396598_dp, &
       5.27281573691989_dp, 3.50663988525637_dp, 2.44257560987167_dp, &
       5.73727394144905_dp, 4.92156143476918_dp, 4.60054725966669_dp], &
      "quadratic LOESS fitted values", allowed_error=tolerance)
   prediction = predict_loess(loess_model, [0.5_dp, 2.5_dp, 5.5_dp, 9.5_dp])
   call assert_vector_close(prediction, &
      [0.380359425777025_dp, 2.08899397526616_dp, 4.13125_dp, &
       6.04910207430933_dp], "quadratic LOESS predictions", allowed_error=tolerance)

   loess_model = loess_fit(x, y, span=0.75_dp, degree=1, family="symmetric")
   call assert_vector_close(loess_model%fitted_values, &
      [0.914942490423344_dp, 2.99406091050011_dp, 1.60300459980155_dp, &
       5.29245627781194_dp, 3.67277490070332_dp, 2.25900363002536_dp, &
       5.70925323560631_dp, 4.84348721958616_dp, 4.31385315243793_dp], &
      "robust LOESS fitted values", allowed_error=tolerance)
   call assert_vector_close(loess_model%robustness, &
      [0.996894910315001_dp, 0.895271207932310_dp, 0.929687938166965_dp, &
       0.896944754954954_dp, 0.999703489957256_dp, 0.716550236626646_dp, &
       0.984135905749545_dp, 0.945216049382716_dp, 0.984935364210552_dp], &
      "robust LOESS weights", allowed_error=tolerance)
   prediction = predict_loess(loess_model, [0.5_dp, 2.5_dp, 5.5_dp, 9.5_dp])
   call assert_vector_close(prediction, &
      [0.564821805531401_dp, 1.93233443510742_dp, 4.02197565231445_dp, &
       5.92033556671115_dp], "robust LOESS predictions", allowed_error=tolerance)

   loess_model = loess_fit(x, y, span=0.75_dp, degree=1, &
      weights=[1.0_dp, 2.0_dp, 0.5_dp, 1.0_dp, 3.0_dp, 1.5_dp, 0.75_dp, 2.5_dp, 1.0_dp])
   call assert_vector_close(loess_model%fitted_values, &
      [1.10932974325469_dp, 3.04526805199534_dp, 1.76238842585297_dp, &
       5.35450350222649_dp, 3.65886170387741_dp, 2.40499709449842_dp, &
       5.74616045031650_dp, 4.90919031571390_dp, 4.34926721289197_dp], &
      "weighted LOESS fitted values", allowed_error=tolerance)
   prediction = predict_loess(loess_model, [0.5_dp, 2.5_dp, 5.5_dp, 9.5_dp])
   call assert_vector_close(prediction, &
      [0.767547742945552_dp, 2.07632327936416_dp, 4.02273843025613_dp, &
       5.93299676985078_dp], "weighted LOESS predictions", allowed_error=tolerance)

   spline_model = smooth_spline(x, y, spar=0.5_dp)
   call assert_integer(spline_model%status, 0, "smoothing spline status")
   call assert_close(spline_model%ratio, 0.000314957184613558_dp, &
                     "smoothing spline ratio", 2.0e-12_dp)
   call assert_close(spline_model%lambda, 0.00503931495381693_dp, &
                     "smoothing spline lambda", 2.0e-12_dp)
   call assert_close(spline_model%degrees_freedom, 3.45530282913025_dp, &
                     "smoothing spline degrees of freedom", 2.0e-8_dp)
   call assert_vector_close_tolerance(spline_model%fitted_values, &
      [0.920326213786204_dp, 1.64532151227386_dp, 2.37248824044812_dp, &
       3.03571818247400_dp, 3.69382544843759_dp, 4.31436201932914_dp, &
       4.84390867909653_dp, 5.30041413880388_dp, 5.77363556535075_dp], &
      "smoothing spline fitted values", 2.0e-8_dp)
   prediction = predict_smooth_spline(spline_model, [0.5_dp, 2.5_dp, 5.5_dp, 9.5_dp])
   call assert_vector_close_tolerance(prediction, &
      [0.560396683258634_dp, 2.01390562739962_dp, 4.01290427241352_dp, &
       6.01431940277586_dp], "smoothing spline predictions", 2.0e-8_dp)
   prediction = predict_smooth_spline( &
      spline_model, [0.5_dp, 1.0_dp, 2.5_dp, 5.5_dp, 9.0_dp, 9.5_dp], derivative=1)
   call assert_vector_close_tolerance(prediction, &
      [0.719859061055141_dp, 0.719859061055141_dp, 0.733088291614682_dp, &
       0.623242453176668_dp, 0.481367674850223_dp, 0.481367674850223_dp], &
      "smoothing spline first derivative", 2.0e-8_dp)
   prediction = predict_smooth_spline( &
      spline_model, [0.5_dp, 1.0_dp, 2.5_dp, 5.5_dp, 9.0_dp, 9.5_dp], derivative=2)
   call assert_vector_close_tolerance(prediction, &
      [0.0_dp, -0.000117664190481_dp, -0.040006008309021_dp, &
       -0.070484308241273_dp, -0.000127429290149_dp, 0.0_dp], &
      "smoothing spline second derivative", 2.0e-8_dp)

   spline_model = smooth_spline(x, y, &
      weights=[1.0_dp, 2.0_dp, 0.5_dp, 1.0_dp, 3.0_dp, 1.5_dp, 0.75_dp, 2.5_dp, 1.0_dp], &
      spar=0.5_dp)
   call assert_close(spline_model%ratio, 0.000383577533346806_dp, &
                     "weighted smoothing spline ratio", 2.0e-12_dp)
   call assert_vector_close_tolerance(spline_model%fitted_values, &
      [1.05462132751704_dp, 1.74407349543286_dp, 2.41193745541628_dp, &
       3.03449153770742_dp, 3.68868116919648_dp, 4.33557669747885_dp, &
       4.90862356545817_dp, 5.39239771994273_dp, 5.86116777009428_dp], &
      "weighted smoothing spline fitted values", 2.0e-8_dp)

   spline_model = smooth_spline(x, y, degrees_freedom=4.0_dp)
   call assert_integer(spline_model%status, 0, "df smoothing spline status")
   call assert_close(spline_model%degrees_freedom, 4.0_dp, &
                     "target smoothing spline degrees of freedom", 2.0e-10_dp)

   spline_model = smooth_spline(x, y)
   call assert_integer(spline_model%status, 0, "automatic smoothing spline status")
   if (.not. spline_model%automatic) error stop "automatic smoothing spline selection"
   call assert_close(spline_model%spar, 1.46155314158378_dp, &
                     "automatic smoothing spline spar", 2.0e-2_dp)
   call assert_close(spline_model%gcv, 0.318897970613666_dp, &
                     "automatic smoothing spline GCV", 2.0e-7_dp)
   call assert_close(spline_model%degrees_freedom, 2.00000063719612_dp, &
                     "automatic smoothing spline degrees of freedom", 3.0e-7_dp)
   call assert_vector_close_tolerance(spline_model%fitted_values, &
      [1.10444434550192_dp, 1.71444441416508_dp, 2.32444447449956_dp, &
       2.93444450878313_dp, 3.54444451506109_dp, 4.15444448545934_dp, &
       4.76444441600588_dp, 5.37444431714603_dp, 5.98444421039669_dp], &
      "automatic smoothing spline fitted values", 2.0e-6_dp)
   prediction = predict_smooth_spline(spline_model, [0.5_dp, 2.5_dp, 5.5_dp, 9.5_dp])
   call assert_vector_close_tolerance(prediction, &
      [0.799444310789596_dp, 2.01944444660047_dp, 3.84944450522238_dp, &
       6.28944415671419_dp], "automatic smoothing spline predictions", 2.0e-6_dp)

   spline_model = smooth_spline(x, y, ordinary_cv=.true.)
   call assert_integer(spline_model%status, 0, "ordinary-CV smoothing spline status")
   if (.not. spline_model%automatic .or. .not. spline_model%ordinary_cv) then
      error stop "ordinary-CV smoothing spline selection"
   end if
   call assert_close(spline_model%spar, 0.629017623172734_dp, &
                     "ordinary-CV smoothing spline spar", 2.0e-8_dp)
   call assert_close(spline_model%cv, 0.295140372683523_dp, &
                     "ordinary-CV smoothing spline score", 2.0e-7_dp)
   call assert_close(spline_model%criterion, spline_model%cv, &
                     "ordinary-CV selected criterion", 2.0e-12_dp)
   call assert_vector_close_tolerance(spline_model%fitted_values, &
      [1.02044851633411_dp, 1.68521644623008_dp, 2.34540304728780_dp, &
       2.98744653223464_dp, 3.61326447477025_dp, 4.21637997939836_dp, &
       4.79140217897184_dp, 5.34524360559654_dp, 5.89519521917588_dp], &
      "ordinary-CV smoothing spline fitted values", 5.0e-5_dp)

   spline_model = smooth_spline( &
      x, y, weights=[1.0_dp, 2.0_dp, 0.5_dp, 1.0_dp, 3.0_dp, 1.5_dp, &
                     0.75_dp, 2.5_dp, 1.0_dp], spar=0.5_dp, ordinary_cv=.true.)
   call assert_integer(spline_model%status, 0, "weighted ordinary-CV spline status")
   call assert_close(spline_model%cv, 0.326179463700165_dp, &
                     "weighted ordinary-CV spline score", 2.0e-7_dp)
   call assert_vector_close_tolerance(spline_model%fitted_values, &
      [1.05462132751704_dp, 1.74407349543286_dp, 2.41193745541628_dp, &
       3.03449153770742_dp, 3.68868116919648_dp, 4.33557669747885_dp, &
       4.90862356545817_dp, 5.39239771994273_dp, 5.86116777009428_dp], &
      "weighted ordinary-CV spline fitted values", 2.0e-8_dp)

   spline_model = smooth_spline( &
      [1.0_dp, 1.0_dp, 2.0_dp, 3.0_dp, 3.0_dp, 3.0_dp, 4.0_dp, 5.0_dp, 6.0_dp, 7.0_dp], &
      [1.0_dp, 1.4_dp, 1.8_dp, 3.0_dp, 3.4_dp, 2.8_dp, 4.2_dp, 4.8_dp, 5.5_dp, 7.0_dp], &
      weights=[1.0_dp, 2.0_dp, 1.0_dp, 0.5_dp, 2.0_dp, 1.5_dp, 1.0_dp, 1.0_dp, 2.0_dp, 1.0_dp], &
      spar=0.5_dp)
   call assert_integer(spline_model%status, 0, "duplicate smoothing spline status")
   call assert_integer(spline_model%n_original, 10, "duplicate smoothing spline original count")
   call assert_vector_close_tolerance(spline_model%x, &
      [1.0_dp, 2.0_dp, 3.0_dp, 4.0_dp, 5.0_dp, 6.0_dp, 7.0_dp], &
      "duplicate smoothing spline predictors", 2.0e-12_dp)
   call assert_vector_close_tolerance(spline_model%y, &
      [1.26666666666667_dp, 1.8_dp, 3.125_dp, 4.2_dp, 4.8_dp, 5.5_dp, 7.0_dp], &
      "duplicate smoothing spline responses", 2.0e-12_dp)
   call assert_vector_close_tolerance(spline_model%weights, &
      [2.30769230769231_dp, 0.769230769230769_dp, 3.07692307692308_dp, &
       0.769230769230769_dp, 0.769230769230769_dp, 1.53846153846154_dp, &
       0.769230769230769_dp], "duplicate smoothing spline weights", 2.0e-12_dp)
   call assert_close(spline_model%lambda, 0.0155224240365898_dp, &
                     "duplicate smoothing spline lambda", 2.0e-10_dp)
   call assert_close(spline_model%degrees_freedom, 2.89792799548021_dp, &
                     "duplicate smoothing spline degrees of freedom", 2.0e-8_dp)
   call assert_vector_close_tolerance(spline_model%fitted_values, &
      [1.2318058615103_dp, 2.14279230194065_dp, 3.06469139742409_dp, &
       3.96513859016569_dp, 4.84458463656369_dp, 5.74694279035094_dp, &
       6.69941571640104_dp], "duplicate smoothing spline fitted values", 2.0e-8_dp)
   prediction = predict_smooth_spline(spline_model, [0.5_dp, 1.0_dp, 2.5_dp, 7.5_dp])
   call assert_vector_close_tolerance(prediction, &
      [0.778308119504184_dp, 1.2318058615103_dp, 2.60415688029322_dp, &
       7.18138748243484_dp], "duplicate smoothing spline predictions", 2.0e-8_dp)

   spline_model = smooth_spline( &
      [1.0_dp, 1.0_dp, 2.0_dp, 3.0_dp, 3.0_dp, 3.0_dp, 4.0_dp, 5.0_dp, 6.0_dp, 7.0_dp], &
      [1.0_dp, 1.4_dp, 1.8_dp, 3.0_dp, 3.4_dp, 2.8_dp, 4.2_dp, 4.8_dp, 5.5_dp, 7.0_dp], &
      weights=[1.0_dp, 2.0_dp, 1.0_dp, 0.5_dp, 2.0_dp, 1.5_dp, 1.0_dp, 1.0_dp, 2.0_dp, 1.0_dp], &
      spar=0.5_dp, ordinary_cv=.true.)
   call assert_close(spline_model%cv, 0.158694475659011_dp, &
                     "duplicate ordinary-CV spline score", 2.0e-7_dp)
   call assert_vector_close_tolerance(spline_model%fitted_values, &
      [1.2318058615103_dp, 2.14279230194065_dp, 3.06469139742409_dp, &
       3.96513859016569_dp, 4.84458463656369_dp, 5.74694279035094_dp, &
       6.69941571640104_dp], "duplicate ordinary-CV spline fitted values", 2.0e-8_dp)

   spline_model = smooth_spline( &
      [1.0_dp, 1.0000002_dp, 2.0_dp, 3.0_dp, 4.0_dp, 5.0_dp], &
      [1.0_dp, 1.4_dp, 2.0_dp, 3.2_dp, 3.8_dp, 5.1_dp], &
      spar=0.5_dp, all_knots=.true.)
   call assert_integer(spline_model%status, 0, "tolerance-grouped spline status")
   call assert_close(spline_model%tolerance, 2.49999985e-6_dp, &
                     "default smoothing spline tolerance", 2.0e-14_dp)
   call assert_vector_close_tolerance(spline_model%x, &
      [1.0_dp, 2.0_dp, 3.0_dp, 4.0_dp, 5.0_dp], &
      "tolerance-grouped smoothing spline predictors", 2.0e-12_dp)
   call assert_vector_close_tolerance(spline_model%y, &
      [1.2_dp, 2.0_dp, 3.2_dp, 3.8_dp, 5.1_dp], &
      "tolerance-grouped smoothing spline responses", 2.0e-12_dp)
   call assert_vector_close_tolerance(spline_model%weights, &
      [2.0_dp, 1.0_dp, 1.0_dp, 1.0_dp, 1.0_dp], &
      "tolerance-grouped smoothing spline weights", 2.0e-12_dp)
   call assert_close(spline_model%ratio, 0.001898169205171864_dp, &
                     "tolerance-grouped spline ratio", 2.0e-11_dp)
   call assert_close(spline_model%degrees_freedom, 2.484595094616907_dp, &
                     "tolerance-grouped spline degrees of freedom", 2.0e-8_dp)
   call assert_vector_close_tolerance(spline_model%fitted_values, &
      [1.17453656700533_dp, 2.10188218946905_dp, 3.04671002936404_dp, &
       4.00464083682212_dp, 4.99769381033411_dp], &
      "tolerance-grouped spline fitted values", 2.0e-8_dp)
   prediction = predict_smooth_spline(spline_model, [0.5_dp, 1.0_dp, 2.5_dp, 5.5_dp])
   call assert_vector_close_tolerance(prediction, &
      [0.713042757078134_dp, 1.17453656700533_dp, 2.57266066724485_dp, &
       5.49859766468404_dp], "tolerance-grouped spline predictions", 2.0e-8_dp)
   spline_model = smooth_spline( &
      [1.0_dp, 1.0000002_dp, 2.0_dp, 3.0_dp, 4.0_dp, 5.0_dp], &
      [1.0_dp, 1.4_dp, 2.0_dp, 3.2_dp, 3.8_dp, 5.1_dp], &
      spar=0.5_dp, all_knots=.true., tolerance=1.0e-8_dp)
   call assert_integer(size(spline_model%x), 6, "explicit spline grouping tolerance")

   do i = 1, size(x_large)
      x_large(i) = real(i, dp)
      y_large(i) = sin(x_large(i)/7.0_dp) + 0.015_dp*x_large(i) + &
                   0.2_dp*cos(x_large(i)/3.0_dp)
   end do
   spline_model = smooth_spline(x_large, y_large, spar=0.5_dp)
   call assert_integer(spline_model%status, 0, "reduced-knot smoothing spline status")
   call assert_integer(spline_model%n_knots, 53, "default reduced-knot count")
   call assert_integer(size(spline_model%knots), 59, "default reduced knot-vector size")
   call assert_close(spline_model%ratio, 1.2998834172577614e-6_dp, &
                     "reduced-knot smoothing spline ratio", 2.0e-14_dp)
   call assert_close(spline_model%degrees_freedom, 15.839850317914332_dp, &
                     "reduced-knot smoothing spline degrees of freedom", 2.0e-7_dp)
   call assert_vector_close_tolerance( &
      [spline_model%fitted_values(1), spline_model%fitted_values(8), &
       spline_model%fitted_values(16), spline_model%fitted_values(32), &
       spline_model%fitted_values(48), spline_model%fitted_values(64)], &
      [0.372748201614960_dp, 0.859558215319051_dp, 1.10286983935934_dp, &
       -0.568654226045573_dp, 1.08180488805302_dp, 1.09254320258261_dp], &
      "reduced-knot smoothing spline fitted values", 2.0e-7_dp)
   prediction = predict_smooth_spline(spline_model, [0.5_dp, 10.5_dp, 33.3_dp, 64.5_dp])
   call assert_vector_close_tolerance(prediction, &
      [0.325753117840909_dp, 0.977280005925508_dp, -0.477738546515203_dp, &
       1.00738783560320_dp], "reduced-knot smoothing spline predictions", 2.0e-7_dp)

   spline_model = smooth_spline(x_large, y_large, spar=0.5_dp, n_knots=20)
   call assert_integer(spline_model%n_knots, 20, "explicit reduced-knot count")
   call assert_close(spline_model%ratio, 7.9033483011499843e-5_dp, &
                     "explicit reduced-knot ratio", 2.0e-12_dp)
   call assert_close(spline_model%degrees_freedom, 6.325321274072036_dp, &
                     "explicit reduced-knot degrees of freedom", 2.0e-8_dp)

   spline_model = smooth_spline(x_large, y_large, spar=0.5_dp, all_knots=.true.)
   call assert_integer(spline_model%n_knots, 64, "all-knots override count")
   call assert_close(spline_model%ratio, 7.4015918369966635e-7_dp, &
                     "all-knots smoothing spline ratio", 2.0e-14_dp)

   prediction = predict_smooth_spline(spline_model, [2.0_dp], derivative=3)
   if (.not. all(ieee_is_nan(prediction))) error stop "invalid spline derivative order"

   print *, "test_smoothing: PASS"

end program test_smoothing
