program test_rank_exact_tests
   use stats_test_assertions, only: assert_close, assert_close_tolerance, assert_integer
   use r_stats, only: dp, fisher_test, fisher_test_result_t, kruskal_test, &
                      kruskal_test_result_t, ks_test, ks_test_result_t, wilcox_test, &
                      wilcox_test_result_t
   implicit none

   real(dp), parameter :: tolerance = 4.0e-8_dp
   integer, parameter :: fisher_table(2, 2) = reshape([1, 11, 9, 3], [2, 2])
   real(dp), parameter :: ks_x(5) = [0.1_dp, 0.4_dp, 0.8_dp, 1.2_dp, 1.5_dp]
   real(dp), parameter :: ks_y(6) = [0.2_dp, 0.3_dp, 0.9_dp, 1.1_dp, 1.7_dp, 2.0_dp]
   real(dp), parameter :: kruskal_values(9) = [1.0_dp, 2.0_dp, 2.0_dp, 4.0_dp, &
                                               5.0_dp, 6.0_dp, 6.0_dp, 8.0_dp, 9.0_dp]
   integer, parameter :: kruskal_groups(9) = [1, 1, 1, 2, 2, 2, 3, 3, 3]
   type(fisher_test_result_t) :: fisher_result
   type(kruskal_test_result_t) :: kruskal_result
   type(ks_test_result_t) :: ks_result
   type(wilcox_test_result_t) :: wilcox_result

   ! Reference values generated by R 4.6.0 stats functions.
   fisher_result = fisher_test(fisher_table)
   call assert_close(fisher_result%p_value, 0.002759456185220084_dp, "Fisher p-value", &
      allowed_error=tolerance)
   ! R's default uniroot tolerance gives a slightly less converged conditional MLE.
   call assert_close_tolerance(fisher_result%estimate, 0.037233117250979192_dp, &
                               3.0e-5_dp, "Fisher odds ratio")

   wilcox_result = wilcox_test([1.0_dp, 2.0_dp, 3.0_dp, 4.0_dp, 5.0_dp], &
                               [6.0_dp, 7.0_dp, 8.0_dp, 9.0_dp])
   call assert_close(wilcox_result%statistic, 0.0_dp, "rank-sum statistic", allowed_error=tolerance)
   call assert_close(wilcox_result%p_value, 0.019964453305216061_dp, "rank-sum p-value", &
      allowed_error=tolerance)
   call assert_integer(wilcox_result%method, 1, "rank-sum method")

   wilcox_result = wilcox_test([5.0_dp, 7.0_dp, 8.0_dp, 6.0_dp, 9.0_dp], &
                               [3.0_dp, 6.0_dp, 7.0_dp, 7.0_dp, 5.0_dp], paired=.true.)
   call assert_close(wilcox_result%statistic, 13.0_dp, "signed-rank statistic", &
      allowed_error=tolerance)
   call assert_close(wilcox_result%p_value, 0.1695641451905634_dp, "signed-rank p-value", &
      allowed_error=tolerance)
   call assert_integer(wilcox_result%method, 2, "signed-rank method")

   kruskal_result = kruskal_test(kruskal_values, kruskal_groups)
   call assert_close(kruskal_result%statistic, 6.9378531073446341_dp, "Kruskal statistic", &
      allowed_error=tolerance)
   call assert_close(kruskal_result%p_value, 0.031150451057644215_dp, "Kruskal p-value", &
      allowed_error=tolerance)
   call assert_integer(kruskal_result%parameter, 2, "Kruskal degrees of freedom")

   ks_result = ks_test(ks_x, mean=0.5_dp, sd=0.7_dp)
   call assert_close(ks_result%statistic, 0.28385458309867628_dp, "one-sample KS statistic", &
      allowed_error=tolerance)
   call assert_close(ks_result%p_value, 0.81525681690755192_dp, "one-sample KS p-value", &
      allowed_error=tolerance)
   call assert_integer(ks_result%n, 5, "one-sample KS sample size")
   call assert_integer(ks_result%method, 1, "one-sample KS method")

   ks_result = ks_test(ks_x, ks_y)
   call assert_close(ks_result%statistic, 0.33333333333333343_dp, "two-sample KS statistic", &
      allowed_error=tolerance)
   call assert_close(ks_result%p_value, 0.92233200785678104_dp, "two-sample KS p-value", &
      allowed_error=tolerance)
   call assert_integer(ks_result%n, 11, "two-sample KS combined size")
   call assert_integer(ks_result%method, 2, "two-sample KS method")

   print *, "test_rank_exact_tests: PASS"

end program test_rank_exact_tests
