program test_decomposition
   use stats_test_assertions, only: assert_integer, assert_vector_close
   use, intrinsic :: ieee_arithmetic, only: ieee_is_nan
   use r_stats, only: decompose, dp, seasonal_decomposition_t
   implicit none

   real(dp), parameter :: tolerance = 5.0e-11_dp
   real(dp) :: x(16), y(12)
   type(seasonal_decomposition_t) :: result

   x = [12.0_dp, 15.0_dp, 14.0_dp, 18.0_dp, 13.0_dp, 17.0_dp, 16.0_dp, 20.0_dp, &
        15.0_dp, 19.0_dp, 18.0_dp, 22.0_dp, 17.0_dp, 21.0_dp, 20.0_dp, 24.0_dp]

   ! Reference values generated by R 4.6.1 stats::decompose.
   result = decompose(x, 4)
   call assert_integer(result%status, 0, "additive status")
   if (.not. all(ieee_is_nan(result%trend([1, 2, 15, 16])))) then
      error stop "additive trend endpoints"
   end if
   call assert_vector_close(result%trend(3:14), &
      [14.875_dp, 15.25_dp, 15.75_dp, 16.25_dp, 16.75_dp, 17.25_dp, &
       17.75_dp, 18.25_dp, 18.75_dp, 19.25_dp, 19.75_dp, 20.25_dp], &
      "additive trend", allowed_error=tolerance)
   call assert_vector_close(result%figure, &
      [-2.73958333333333_dp, 0.760416666666667_dp, -0.78125_dp, &
       2.76041666666667_dp], "additive figure", allowed_error=tolerance)
   call assert_vector_close(result%random(3:14), &
      [-0.09375_dp, -0.0104166666666661_dp, -0.0104166666666661_dp, &
       -0.0104166666666679_dp, 0.03125_dp, -0.0104166666666679_dp, &
       -0.0104166666666679_dp, -0.0104166666666679_dp, 0.03125_dp, &
       -0.0104166666666679_dp, -0.0104166666666679_dp, &
       -0.0104166666666679_dp], "additive random component", allowed_error=tolerance)

   result = decompose(x, 4, multiplicative=.true.)
   call assert_integer(result%status, 0, "multiplicative status")
   call assert_vector_close(result%figure, &
      [0.8441277907548_dp, 1.0419047999686_dp, 0.95256852273548_dp, &
       1.16139888654112_dp], "multiplicative figure", allowed_error=tolerance)
   call assert_vector_close(result%random(3:14), &
      [0.988040700615919_dp, 1.01629843332097_dp, 0.97781027284835_dp, &
       1.00407815203978_dp, 1.00278757674452_dp, 0.998296367674383_dp, &
       1.0011166932196_dp, 0.999223624310335_dp, 1.00780151462824_dp, &
       0.98403499099332_dp, 1.01970282592072_dp, 0.99532801563856_dp], &
      "multiplicative random component", allowed_error=tolerance)

   result = decompose(x, 4, filter=[0.1_dp, 0.2_dp, 0.3_dp, 0.4_dp])
   call assert_integer(result%status, 0, "custom-filter status")
   if (.not. all(ieee_is_nan(result%trend([1, 15, 16])))) then
      error stop "custom-filter trend endpoints"
   end if
   call assert_vector_close(result%trend(2:14), &
      [13.9_dp, 15.1_dp, 15.3_dp, 16.1_dp, 15.5_dp, 17.1_dp, 17.3_dp, &
       18.1_dp, 17.5_dp, 19.1_dp, 19.3_dp, 20.1_dp, 19.5_dp], &
      "custom-filter trend", allowed_error=tolerance)
   call assert_vector_close(result%figure, &
      [-3.075_dp, 1.425_dp, -1.075_dp, 2.725_dp], "custom-filter figure", allowed_error=tolerance)
   call assert_vector_close(result%random(2:14), &
      [-0.325000000000003_dp, -0.0250000000000004_dp, -0.0250000000000021_dp, &
       -0.0250000000000021_dp, 0.0749999999999993_dp, -0.0250000000000021_dp, &
       -0.0250000000000021_dp, -0.0250000000000021_dp, 0.0749999999999993_dp, &
       -0.0250000000000021_dp, -0.0250000000000021_dp, -0.0250000000000021_dp, &
       0.0749999999999993_dp], "custom-filter random component", allowed_error=tolerance)

   y = [8.0_dp, 11.0_dp, 10.0_dp, 9.0_dp, 12.0_dp, 11.0_dp, &
        10.0_dp, 13.0_dp, 12.0_dp, 11.0_dp, 14.0_dp, 13.0_dp]
   result = decompose(y, 3)
   call assert_integer(result%status, 0, "odd-period status")
   call assert_vector_close(result%trend(2:11), &
      [9.66666666666667_dp, 10.0_dp, 10.3333333333333_dp, &
       10.6666666666667_dp, 11.0_dp, 11.3333333333333_dp, &
       11.6666666666667_dp, 12.0_dp, 12.3333333333333_dp, &
       12.6666666666667_dp], "odd-period trend", allowed_error=tolerance)
   call assert_vector_close(result%figure, &
      [-1.33333333333333_dp, 1.33333333333333_dp, 0.0_dp], &
      "odd-period figure", allowed_error=tolerance)

   result = decompose(x(:7), 4)
   call assert_integer(result%status, 1, "insufficient cycles")

   print *, "test_decomposition: PASS"

end program test_decomposition
