program test_stl
   use stats_test_assertions, only: assert_integer, assert_integer_vector, assert_vector_approx
   use r_stats, only: dp, stl, stl_result_t
   implicit none

   real(dp) :: x(24)
   type(stl_result_t) :: result

   x = [10.0_dp, 13.0_dp, 12.0_dp, 16.0_dp, 11.0_dp, 15.0_dp, &
        14.0_dp, 18.0_dp, 13.0_dp, 16.0_dp, 15.0_dp, 20.0_dp, &
        14.0_dp, 18.0_dp, 17.0_dp, 21.0_dp, 16.0_dp, 19.0_dp, &
        18.0_dp, 23.0_dp, 17.0_dp, 21.0_dp, 20.0_dp, 24.0_dp]

   ! Reference values generated by R 4.6.1 stats::stl with s.window=7.
   result = stl(x, 4, s_window=7)
   call assert_integer(result%status, 0, "default status")
   call assert_integer_vector(result%window, [7, 9, 5], "default windows")
   call assert_vector_approx(result%seasonal, &
      [-2.56400921543599_dp, 0.487442509119644_dp, -0.91366109044748_dp, &
       3.00266286382494_dp, -2.57925771558482_dp, 0.485281338356391_dp, &
       -0.91745575459741_dp, 3.02179316648404_dp, -2.62310136319524_dp, &
       0.495437202587494_dp, -0.923684203276011_dp, 3.08628991776236_dp, &
       -2.64649883727809_dp, 0.463035568843023_dp, -0.944267278694259_dp, &
       3.18710523893345_dp, -2.7171650958286_dp, 0.477889018429509_dp, &
       -0.910290979032355_dp, 3.1649148696506_dp, -2.73576630570876_dp, &
       0.480542137225935_dp, -0.902350455049415_dp, 3.16142180832256_dp], &
      2.0e-9_dp, "default seasonal")
   call assert_vector_approx(result%trend, &
      [12.2665903051588_dp, 12.6178084445553_dp, 12.9858816223941_dp, &
       13.3644577313821_dp, 13.763119333815_dp, 14.2321628681026_dp, &
       14.7000330035631_dp, 15.0886257116765_dp, 15.4149976766613_dp, &
       15.7659906629071_dp, 16.1300842537202_dp, 16.5304656530337_dp, &
       16.9689316766363_dp, 17.3692414688395_dp, 17.7386317251621_dp, &
       18.0858309082864_dp, 18.4044698259086_dp, 18.7559575988209_dp, &
       19.1335026318206_dp, 19.5312968956046_dp, 19.9405420469674_dp, &
       20.3242139035922_dp, 20.7067856315826_dp, 21.0851495732226_dp], &
      2.0e-9_dp, "default trend")
   call assert_vector_approx(result%remainder, &
      [0.297418910277221_dp, -0.105250953674926_dp, -0.0722205319466056_dp, &
       -0.367120595207016_dp, -0.183861618230205_dp, 0.282555793541029_dp, &
       0.217422751034285_dp, -0.110418878160564_dp, 0.208103686533919_dp, &
       -0.261427865494559_dp, -0.206400050444238_dp, 0.383244429203977_dp, &
       -0.322432839358214_dp, 0.167722962317452_dp, 0.20563555353219_dp, &
       -0.272936147219806_dp, 0.312695269919992_dp, -0.233846617250396_dp, &
       -0.223211652788223_dp, 0.303788234744768_dp, -0.204775741258612_dp, &
       0.195243959181852_dp, 0.195564823466785_dp, -0.246571381545206_dp], &
      2.0e-9_dp, "default remainder")
   if (any(result%weights /= 1.0_dp)) error stop "default robustness weights"

   result = stl(x, 4, periodic=.true.)
   call assert_integer(result%status, 0, "periodic status")
   call assert_integer_vector(result%window, [241, 7, 5], "periodic windows")
   call assert_integer_vector(result%jump, [25, 1, 1], "periodic jumps")
   call assert_vector_approx(result%seasonal(:4), &
      [-2.73597339910185_dp, 0.431151786170925_dp, -0.851563836244344_dp, &
       3.15638765859601_dp], 2.0e-9_dp, "periodic seasonal figure")
   if (any(abs(result%seasonal(5:) - result%seasonal(:20)) > 2.0e-9_dp)) then
      error stop "periodic seasonal repetition"
   end if
   call assert_vector_approx(result%trend([1, 7, 12, 18, 24]), &
      [12.5145254942823_dp, 14.7539110226069_dp, 16.5066866665457_dp, &
       18.7391638775632_dp, 21.0217039097314_dp], 2.0e-9_dp, "periodic trend")

   result = stl(x, 4, s_window=7, robust=.true., outer=3)
   call assert_integer(result%status, 0, "robust status")
   call assert_integer(result%inner, 1, "robust inner iterations")
   call assert_vector_approx(result%seasonal([1, 6, 12, 18, 24]), &
      [-2.54717172096158_dp, 0.487444617320368_dp, 3.09074540583748_dp, &
       0.470669742208015_dp, 3.1382500810106_dp], 1.0e-4_dp, "robust seasonal")
   call assert_vector_approx(result%trend([1, 6, 12, 18, 24]), &
      [12.2524210277529_dp, 14.2292221617853_dp, 16.5249294280143_dp, &
       18.7522083911962_dp, 21.0984969077048_dp], 1.0e-4_dp, "robust trend")
   call assert_vector_approx(result%weights([1, 6, 12, 18, 24]), &
      [0.901520971823381_dp, 0.909165299744385_dp, 0.842958341773477_dp, &
       0.943756751174598_dp, 0.934067937109175_dp], 1.0e-4_dp, &
      "robust weights")

   print *, "test_stl: PASS"

end program test_stl
