program test_autoregression
   use stats_test_assertions, only: assert_approx, assert_close, assert_integer, &
                                      assert_vector_approx, assert_vector_close
   use, intrinsic :: ieee_arithmetic, only: ieee_is_nan
   use r_stats, only: ar, ar_fit_t, dp, spec_ar, spectrum_result_t
   implicit none

   real(dp), parameter :: tolerance = 5.0e-11_dp
   real(dp) :: x(16)
   type(ar_fit_t) :: fit
   type(spectrum_result_t) :: estimate

   x = [2.0_dp, 1.0_dp, 4.0_dp, 3.0_dp, 7.0_dp, 5.0_dp, 8.0_dp, 6.0_dp, &
        5.0_dp, 4.0_dp, 7.0_dp, 9.0_dp, 6.0_dp, 3.0_dp, 2.0_dp, 1.0_dp]

   ! Reference values generated by R 4.6.0 stats::ar with method="yule-walker".
   fit = ar(x, order=2)
   call assert_integer(fit%status, 0, "fixed AR status")
   call assert_integer(fit%order, 2, "fixed AR order")
   call assert_vector_close(fit%coefficients, &
      [0.51899718289042940_dp, -0.11461973688376172_dp], "fixed AR coefficients", &
      allowed_error=tolerance)
   call assert_close(fit%variance, 5.4660525498756707_dp, "fixed AR variance", &
      allowed_error=tolerance)
   call assert_close(fit%mean, 4.5625_dp, "fixed AR mean", allowed_error=tolerance)
   call assert_vector_close(fit%aic, &
      [1.9100510824811678_dp, 0.0_dp, 1.7884040507069514_dp], "fixed AR AIC", &
      allowed_error=tolerance)
   if (.not. all(ieee_is_nan(fit%residuals(:2)))) error stop "fixed AR initial residuals"
   call assert_vector_close(fit%residuals(3:), &
      [0.99271438828251535_dp, -1.6788968972725347_dp, 3.1839594962691797_dp, &
       -1.0066489721762995_dp, 3.4898243411396064_dp, -0.29640668129920533_dp, &
       0.085446895132938572_dp, -0.62479539574415544_dp, 2.7795820502625124_dp, &
       3.1079707647074621_dp, -0.58616439042211133_dp, -1.7999333679832996_dp, &
       -1.5868010299632966_dp, -2.4116630577241520_dp], "fixed AR residuals", &
      allowed_error=tolerance)

   fit = ar(x, order_max=5)
   call assert_integer(fit%order, 1, "AIC-selected AR order")
   call assert_vector_close(fit%coefficients, [0.46562712440516657_dp], &
                            "AIC-selected AR coefficient", allowed_error=tolerance)
   call assert_close(fit%variance, 5.1431898280256076_dp, "AIC-selected AR variance", &
      allowed_error=tolerance)
   call assert_vector_close(fit%aic, &
      [1.9100510824811678_dp, 0.0_dp, 1.7884040507069514_dp, 1.6095835702806802_dp, &
       3.2638373652245676_dp, 5.2134513538839720_dp], "selected AR AIC", allowed_error=tolerance)

   fit = ar(x, order=2, method="burg")
   call assert_integer(fit%status, 0, "fixed Burg status")
   call assert_vector_close(fit%coefficients, &
      [0.55362272175471017_dp, -0.064457009772196205_dp], "fixed Burg coefficients", &
      allowed_error=tolerance)
   call assert_close(fit%variance, 4.1743445050488690_dp, "fixed Burg variance", &
      allowed_error=tolerance)
   call assert_vector_close(fit%aic, &
      [3.0463931847003565_dp, 0.0_dp, 1.9333862259113843_dp], "fixed Burg AIC", &
      allowed_error=tolerance)

   fit = ar(x, order=2, method="burg", variance_method=2)
   call assert_close(fit%variance, 4.0762944574211462_dp, "Burg residual variance", &
      allowed_error=tolerance)
   call assert_vector_close(fit%aic, &
      [3.7839124676897988_dp, 0.0_dp, 2.2906017219474819_dp], &
      "Burg residual-variance AIC", allowed_error=tolerance)

   fit = ar(x, order_max=5, method="burg")
   call assert_integer(fit%order, 1, "AIC-selected Burg order")
   call assert_close(fit%coefficients(1), 0.52009871387214657_dp, &
                     "AIC-selected Burg coefficient", allowed_error=tolerance)
   call assert_close(fit%variance, 4.1917600360772695_dp, "AIC-selected Burg variance", &
      allowed_error=tolerance)
   call assert_vector_close(fit%aic, &
      [3.0463931847003565_dp, 0.0_dp, 1.9333862259113843_dp, &
       0.026355194184414898_dp, 1.2847615476673333_dp, 2.8537028553294732_dp], &
      "selected Burg AIC", allowed_error=tolerance)

   fit = ar(x, order=2, method="ols")
   call assert_integer(fit%status, 0, "fixed OLS status")
   call assert_vector_close(fit%coefficients, &
      [0.48007108403148024_dp, -0.08403148007108413_dp], "fixed OLS coefficients", &
      allowed_error=tolerance)
   call assert_close(fit%variance, 3.9910056939759904_dp, "fixed OLS variance", &
      allowed_error=tolerance)
   call assert_close(fit%intercept, 0.2642326732673268_dp, "fixed OLS intercept", &
      allowed_error=tolerance)
   call assert_vector_close(fit%aic, [0.0_dp], "fixed OLS AIC", allowed_error=tolerance)
   call assert_integer(fit%aic_order(1), 2, "fixed OLS AIC order")

   fit = ar(x, order_max=5, method="ols")
   call assert_integer(fit%order, 4, "AIC-selected OLS order")
   call assert_vector_close(fit%coefficients, &
      [0.49859992722117019_dp, -0.089157125597657372_dp, &
       -0.65234403819145781_dp, 0.13201921567186381_dp], "selected OLS coefficients", &
      allowed_error=tolerance)
   call assert_close(fit%variance, 2.6570161245236847_dp, "selected OLS variance", &
      allowed_error=tolerance)
   call assert_close(fit%intercept, 0.8410776523389667_dp, "selected OLS intercept", &
      allowed_error=tolerance)
   call assert_vector_close(fit%aic, &
      [4.3410646506753672_dp, 1.1263847674544412_dp, 2.5094322770399398_dp, &
       1.1473176596037611_dp, 0.0_dp, 3.0983481200854150_dp], "selected OLS AIC", &
      allowed_error=tolerance)

   fit = ar(x, order=2, method="mle")
   call assert_integer(fit%status, 0, "fixed MLE status")
   call assert_vector_approx(fit%coefficients, &
      [0.57003170760065092_dp, -0.03512737238077019_dp], 2.0e-4_dp, &
      "fixed MLE coefficients")
   call assert_approx(fit%variance, 4.1335136844740221_dp, 2.0e-4_dp, &
                      "fixed MLE variance")
   call assert_approx(fit%mean, 4.1988454238853930_dp, 2.0e-3_dp, "fixed MLE mean")

   fit = ar(x, order_max=5, method="mle")
   call assert_integer(fit%order, 1, "AIC-selected MLE order")
   call assert_approx(fit%coefficients(1), 0.55623595844049711_dp, 1.0e-4_dp, &
                      "AIC-selected MLE coefficient")
   call assert_approx(fit%variance, 4.1358714465928070_dp, 1.0e-4_dp, &
                      "AIC-selected MLE variance")
   call assert_approx(fit%mean, 4.1489295322497899_dp, 2.0e-3_dp, &
                      "AIC-selected MLE mean")
   call assert_vector_approx(fit%aic, &
      [2.8909632983900764_dp, 0.0_dp, 1.9844915955830089_dp, &
       0.8321907278484133_dp, 2.3478162814644747_dp, 4.0223903708862565_dp], &
      3.0e-4_dp, "selected MLE AIC")

   estimate = spec_ar(x, order=2, n_frequency=8)
   call assert_integer(estimate%status, 0, "AR spectrum status")
   call assert_integer(estimate%order, 2, "AR spectrum order")
   call assert_vector_close(estimate%frequency, &
      [0.0_dp, 0.071428571428571425_dp, 0.14285714285714285_dp, &
       0.21428571428571427_dp, 0.28571428571428570_dp, 0.35714285714285710_dp, &
       0.42857142857142855_dp, 0.5_dp], "AR spectrum frequencies", allowed_error=tolerance)
   call assert_vector_close(estimate%spectrum, &
      [15.407477196423375_dp, 14.270516000469570_dp, 10.715086006447935_dp, &
       6.6780660677892589_dp, 4.0993099901964403_dp, 2.7990222442206236_dp, &
       2.2149340517606633_dp, 2.0482046930397360_dp], "AR spectrum", allowed_error=tolerance)

   estimate = spec_ar(x, order=2, n_frequency=8, method="burg")
   call assert_vector_close(estimate%spectrum, &
      [15.996619251445797_dp, 12.682818444064933_dp, 7.6297775692635756_dp, &
       4.4777633147317486_dp, 2.8654758054422493_dp, 2.0697641930523085_dp, &
       1.7017823781135912_dp, 1.5943675714762304_dp], "Burg AR spectrum", allowed_error=tolerance)

   estimate = spec_ar(x, order=2, n_frequency=8, method="ols")
   call assert_vector_close(estimate%spectrum, &
      [10.941211793670814_dp, 9.8649367159793311_dp, 7.2407254676305239_dp, &
       4.6705478075807063_dp, 3.0287315208586110_dp, 2.1583791362375795_dp, &
       1.7503908850018948_dp, 1.6313678206228108_dp], "OLS AR spectrum", allowed_error=tolerance)

   estimate = spec_ar(x, order=2, n_frequency=8, method="mle")
   call assert_vector_approx(estimate%spectrum, &
      [19.108860805988577_dp, 13.476063114183891_dp, 7.1918482157779442_dp, &
       4.1323839973491703_dp, 2.7096619186318325_dp, 2.0199702835492799_dp, &
       1.6987859368980098_dp, 1.6042912695985907_dp], 2.0e-2_dp, &
      "MLE AR spectrum")

   print *, "test_autoregression: PASS"

end program test_autoregression
