program test_spectral
   use stats_test_assertions, only: assert_close, assert_integer, assert_vector_close
   use r_stats, only: dp, multivariate_spectrum_result_t, spec_pgram, spectrum, spectrum_result_t
   implicit none

   real(dp), parameter :: tolerance = 5.0e-11_dp
   real(dp) :: multivariate_x(16, 2), x(16), x_padded(17)
   type(multivariate_spectrum_result_t) :: multivariate_estimate
   type(spectrum_result_t) :: estimate

   x = [2.0_dp, 1.0_dp, 4.0_dp, 3.0_dp, 7.0_dp, 5.0_dp, 8.0_dp, 6.0_dp, &
        5.0_dp, 4.0_dp, 7.0_dp, 9.0_dp, 6.0_dp, 3.0_dp, 2.0_dp, 1.0_dp]

   ! Reference values generated by R 4.6.0 stats::spec.pgram.
   estimate = spec_pgram(x, taper=0.0_dp, detrend=.false., demean=.true., fast=.false.)
   call assert_integer(estimate%status, 0, "raw periodogram status")
   call assert_vector_close(estimate%frequency, &
      [0.0625_dp, 0.125_dp, 0.1875_dp, 0.25_dp, 0.3125_dp, 0.375_dp, 0.4375_dp, 0.5_dp], &
      "raw periodogram frequencies", allowed_error=tolerance)
   call assert_vector_close(estimate%spectrum, &
      [24.545551299511313_dp, 8.8569173824159204_dp, 4.9649199719277144_dp, &
       2.3125_dp, 0.37670161497743598_dp, 0.018082617584077986_dp, &
       2.3628271135835446_dp, 5.0625_dp], "raw periodogram spectrum", allowed_error=tolerance)
   call assert_close(estimate%degrees_freedom, 2.0_dp, "raw periodogram degrees of freedom", &
      allowed_error=tolerance)
   call assert_close(estimate%bandwidth, 0.018042195912175804_dp, "raw periodogram bandwidth", &
      allowed_error=tolerance)
   if (estimate%smoothed) error stop "raw periodogram smoothing metadata"

   estimate = spec_pgram(x, spans=[3, 5], taper=0.0_dp, detrend=.false., &
                         demean=.true., fast=.false.)
   call assert_integer(estimate%status, 0, "smoothed periodogram status")
   call assert_vector_close(estimate%spectrum, &
      [17.481031051179780_dp, 12.805721752247951_dp, 7.5674352196057342_dp, &
       3.6968665475447144_dp, 1.9549405302302807_dp, 1.7546596601909608_dp, &
       2.1173560238620279_dp, 2.3274263675249109_dp], "smoothed periodogram spectrum", &
      allowed_error=tolerance)
   call assert_vector_close(estimate%kernel, &
      [0.03125_dp, 0.125_dp, 0.21875_dp, 0.25_dp, 0.21875_dp, 0.125_dp, 0.03125_dp], &
      "smoothed periodogram kernel", allowed_error=tolerance)
   call assert_close(estimate%degrees_freedom, 10.448979591836736_dp, &
                     "smoothed periodogram degrees of freedom", allowed_error=tolerance)
   call assert_close(estimate%bandwidth, 0.090210979560879007_dp, &
                     "smoothed periodogram bandwidth", allowed_error=tolerance)
   if (.not. estimate%smoothed) error stop "smoothed periodogram metadata"

   multivariate_x(:, 1) = x
   multivariate_x(:, 2) = [1.0_dp, 3.0_dp, 2.0_dp, 5.0_dp, 4.0_dp, 8.0_dp, &
      6.0_dp, 7.0_dp, 8.0_dp, 5.0_dp, 3.0_dp, 6.0_dp, 9.0_dp, 7.0_dp, 4.0_dp, 2.0_dp]
   multivariate_estimate = spec_pgram(multivariate_x, spans=[3, 5], taper=0.0_dp, &
      detrend=.false., demean=.true., fast=.false.)
   call assert_integer(multivariate_estimate%status, 0, "multivariate periodogram status")
   call assert_vector_close(multivariate_estimate%spectrum(:, 1), estimate%spectrum, &
      "multivariate first autospectrum", allowed_error=tolerance)
   call assert_vector_close(multivariate_estimate%spectrum(:, 2), &
      [14.038129569657119_dp, 11.247313735056022_dp, 7.8090119811580676_dp, &
       4.7518398282201773_dp, 2.7872007230333544_dp, 1.9193913312020561_dp, &
       1.6990678586676182_dp, 1.6880168333723091_dp], "multivariate second autospectrum", &
      allowed_error=tolerance)
   call assert_vector_close(multivariate_estimate%coherence(:, 1, 2), &
      [0.77096248774276066_dp, 0.67335711769651885_dp, 0.58787618269542163_dp, &
       0.58506088985787519_dp, 0.54548247748714429_dp, 0.53115004352591300_dp, &
       0.74314296561816673_dp, 0.83765796197682252_dp], "multivariate coherence", &
      allowed_error=tolerance)
   call assert_vector_close(multivariate_estimate%phase(:7, 1, 2), &
      [0.20180677663852425_dp, 0.45001835528636791_dp, 0.80734995345437455_dp, &
       1.3063367946494031_dp, 1.9356945089170285_dp, 2.7110247989459761_dp, &
       3.0746934137609374_dp], "multivariate phase", allowed_error=tolerance)
   call assert_close(abs(multivariate_estimate%phase(8, 1, 2)), acos(-1.0_dp), &
      "multivariate Nyquist phase", allowed_error=tolerance)
   if (maxval(abs(multivariate_estimate%cross_spectrum(:, 2, 1) - &
      conjg(multivariate_estimate%cross_spectrum(:, 1, 2)))) > tolerance) then
      error stop "Hermitian cross-spectrum metadata"
   end if

   estimate = spectrum(x)
   call assert_vector_close(estimate%spectrum, &
      [19.759421075783688_dp, 5.8331528581244951_dp, 7.6683295757038206_dp, &
       4.1665736607142856_dp, 0.038015628875403940_dp, 0.053071576502295784_dp, &
       3.2731927223558053_dp, 5.1830598507785481_dp], "default tapered periodogram", &
      allowed_error=tolerance)
   call assert_close(estimate%degrees_freedom, 1.7915904936014624_dp, &
                     "tapered periodogram degrees of freedom", allowed_error=tolerance)
   if (.not. estimate%detrended .or. estimate%demeaned) error stop "default detrending metadata"

   x_padded(1:16) = x
   x_padded(17) = 0.5_dp
   estimate = spec_pgram(x_padded, taper=0.0_dp, detrend=.false., demean=.true., fast=.true.)
   call assert_integer(estimate%n_used, 18, "fast periodogram padded length")
   call assert_vector_close(estimate%frequency, &
      [0.055555555555555552_dp, 0.11111111111111111_dp, 0.16666666666666666_dp, &
       0.22222222222222221_dp, 0.27777777777777779_dp, 0.33333333333333337_dp, &
       0.38888888888888884_dp, 0.44444444444444442_dp, 0.5_dp], "padded periodogram frequencies", &
      allowed_error=tolerance)
   call assert_vector_close(estimate%spectrum, &
      [30.913237999648171_dp, 2.8602642134655185_dp, 11.378129452473031_dp, &
       1.7078690805754786_dp, 2.4784715662880275_dp, 1.5251882760024424_dp, &
       1.7470040509984586_dp, 3.4979159630320726_dp, 1.5762263382861796_dp], &
      "padded mixed-radix periodogram", allowed_error=tolerance)

   print *, "test_spectral: PASS"

end program test_spectral
