program test_clustering
   use stats_test_assertions, only: assert_close, assert_integer, assert_integer_matrix, &
                                      assert_integer_vector, assert_matrix_close, &
                                      assert_vector_close
   use r_stats, only: cutree, dist, dist_matrix, dp, hclust, hclust_result_t, &
                      kmeans, kmeans_result_t
   implicit none

   real(dp), parameter :: tolerance = 8.0e-10_dp
   real(dp) :: data(6, 2), initial_centers(2, 2)
   real(dp), allocatable :: condensed(:), distances(:, :)
   type(hclust_result_t) :: tree
   type(kmeans_result_t) :: fit

   data(1, :) = [0.0_dp, 0.0_dp]
   data(2, :) = [0.8_dp, 0.2_dp]
   data(3, :) = [1.1_dp, 1.0_dp]
   data(4, :) = [5.0_dp, 4.8_dp]
   data(5, :) = [5.9_dp, 5.1_dp]
   data(6, :) = [6.2_dp, 6.0_dp]

   ! Reference values generated by R 4.6.0 stats functions.
   condensed = dist(data)
   call assert_vector_close(condensed, &
      [0.82462112512353225_dp, 1.4866068747318506_dp, 6.9310893804653828_dp, &
       7.7987178433380961_dp, 8.6278618440491961_dp, 0.85440037453175322_dp, &
       6.2289646009589745_dp, 7.0724818840347687_dp, 7.9246451024635798_dp, &
       5.4451813560247926_dp, 6.312685640834653_dp, 7.1421285342676377_dp, &
       0.94868329805051399_dp, 1.6970562748477143_dp, 0.94868329805051399_dp], &
      "Euclidean condensed distances", allowed_error=tolerance)
   condensed = dist(data, method="manhattan")
   call assert_vector_close(condensed, &
      [1.0_dp, 2.1_dp, 9.8_dp, 11.0_dp, 12.2_dp, 1.1_dp, 8.8_dp, 10.0_dp, &
       11.2_dp, 7.7_dp, 8.9_dp, 10.1_dp, 1.2_dp, 2.4_dp, 1.2_dp], &
      "Manhattan condensed distances", allowed_error=tolerance)

   initial_centers(1, :) = [0.0_dp, 0.0_dp]
   initial_centers(2, :) = [6.2_dp, 6.0_dp]
   fit = kmeans(data, initial_centers, iter_max=20)
   call assert_integer(fit%status, 0, "k-means status")
   call assert_matrix_close(fit%centers, reshape([0.63333333333333341_dp, &
      5.7_dp, 0.4_dp, 5.3_dp], [2, 2]), "k-means centers", allowed_error=tolerance)
   call assert_integer_vector(fit%cluster, [1, 1, 1, 2, 2, 2], "k-means assignments")
   call assert_integer_vector(fit%size, [3, 3], "k-means sizes")
   call assert_vector_close(fit%withinss, [1.2066666666666668_dp, 1.5600000000000005_dp], &
                            "k-means within sums", allowed_error=tolerance)
   call assert_close(fit%totss, 77.288333333333341_dp, "k-means total sum", allowed_error=tolerance)
   call assert_close(fit%tot_withinss, 2.7666666666666675_dp, "k-means total within sum", &
      allowed_error=tolerance)
   call assert_close(fit%betweenss, 74.521666666666675_dp, "k-means between sum", &
      allowed_error=tolerance)
   call assert_integer(fit%iter, 2, "k-means iterations")

   distances = dist_matrix(data)
   tree = hclust(distances, method="complete")
   call assert_integer(tree%status, 0, "hierarchical clustering status")
   call assert_integer_matrix(tree%merge, reshape([-1, -4, -3, -6, 3, &
                                                    -2, -5, 1, 2, 4], [5, 2]), &
                              "hierarchical merges")
   call assert_vector_close(tree%height, &
      [0.82462112512353225_dp, 0.94868329805051399_dp, 1.4866068747318506_dp, &
       1.6970562748477143_dp, 8.6278618440491961_dp], "hierarchical heights", &
      allowed_error=tolerance)
   call assert_integer_vector(tree%order, [3, 1, 2, 6, 4, 5], "hierarchical order")
   call assert_integer_vector(cutree(tree, k=2), [1, 1, 1, 2, 2, 2], "two-cluster tree cut")

   print *, "test_clustering: PASS"

end program test_clustering
