program test_holt_winters
   use stats_test_assertions, only: assert_approx, assert_close, assert_integer, &
                                      assert_vector_approx, assert_vector_close
   use r_stats, only: dp, holt_winters, holt_winters_auto, holt_winters_fit_t, &
                      holt_winters_forecast_t, holt_winters_optimize, holt_winters_reduced, &
                      predict_holt_winters, predict_holt_winters_interval
   implicit none

   real(dp), parameter :: tolerance = 5.0e-11_dp
   real(dp) :: x(16), y(12), z(8)
   type(holt_winters_fit_t) :: fit
   type(holt_winters_forecast_t) :: prediction

   x = [12.0_dp, 15.0_dp, 14.0_dp, 18.0_dp, 13.0_dp, 17.0_dp, 16.0_dp, 20.0_dp, &
        15.0_dp, 19.0_dp, 18.0_dp, 22.0_dp, 17.0_dp, 21.0_dp, 20.0_dp, 24.0_dp]

   ! References generated by R 4.6.1 stats::HoltWinters with explicit initial states.
   fit = holt_winters(x, 4, 0.4_dp, 0.2_dp, 0.3_dp, 10.0_dp, 0.5_dp, &
                      [-1.0_dp, 0.5_dp, 1.0_dp, -0.5_dp])
   call assert_integer(fit%status, 0, "additive status")
   call assert_vector_close(fit%fitted, &
      [9.5_dp, 13.18_dp, 16.2936_dp, 15.738272_dp, 18.97601344_dp, &
       20.0281772288_dp, 20.379173323776_dp, 19.5598441548595_dp, &
       20.1907066219209_dp, 21.75497154962_dp, 21.6612949671582_dp, &
       21.7432510078091_dp], "additive fitted values", allowed_error=tolerance)
   call assert_vector_close(fit%level, &
      [10.0_dp, 11.9_dp, 14.208_dp, 15.17616_dp, 17.9429632_dp, &
       17.755608064_dp, 18.42930633728_dp, 18.4803519942656_dp, &
       20.2687954529157_dp, 20.0001063923525_dp, 20.450454830956_dp, &
       20.4778761785746_dp], "additive level states", allowed_error=tolerance)
   call assert_close(fit%sse, 92.1749918175731_dp, "additive SSE", allowed_error=tolerance)
   call assert_close(fit%final_level, 21.9396115125602_dp, "additive final level", &
      allowed_error=tolerance)
   call assert_close(fit%final_trend, 0.739575656484501_dp, "additive final trend", &
      allowed_error=tolerance)
   call assert_vector_close(fit%final_season, &
      [-1.66000961114576_dp, 0.866633219884398_dp, 0.219867707631842_dp, &
       1.11255391071964_dp], "additive final season", allowed_error=tolerance)
   call assert_vector_close(predict_holt_winters(fit, 6), &
      [21.0191775578989_dp, 24.2853960454136_dp, 24.3782061896455_dp, &
       26.0104680492178_dp, 23.9774801838369_dp, 27.2436986713516_dp], &
      "additive forecasts", allowed_error=tolerance)
   prediction = predict_holt_winters_interval(fit, 6, 0.9_dp)
   call assert_integer(prediction%status, 0, "additive interval status")
   call assert_vector_approx(prediction%upper, &
      [25.7612662548585_dp, 29.5454819164025_dp, 30.2706211142736_dp, &
       32.6385443023947_dp, 31.8607658591053_dp, 35.9923061246657_dp], &
      2.0e-9_dp, "additive upper intervals")
   call assert_vector_approx(prediction%lower, &
      [16.2770888609394_dp, 19.0253101744247_dp, 18.4857912650174_dp, &
       19.382391796041_dp, 16.0941945085686_dp, 18.4950912180375_dp], &
      2.0e-9_dp, "additive lower intervals")

   fit = holt_winters(x, 4, 0.4_dp, 0.2_dp, 0.3_dp, 10.0_dp, 0.5_dp, &
                      [0.9_dp, 1.05_dp, 1.1_dp, 0.95_dp], multiplicative=.true.)
   call assert_integer(fit%status, 0, "multiplicative status")
   call assert_vector_close(fit%fitted, &
      [9.45_dp, 13.538_dp, 16.8206692063492_dp, 15.2120975330447_dp, &
       18.535497787737_dp, 20.8853143766457_dp, 21.140312443118_dp, &
       18.9558460169068_dp, 19.4688014341578_dp, 22.5080994511602_dp, &
       22.2880440382379_dp, 21.195607073141_dp], "multiplicative fitted values", &
      allowed_error=tolerance)
   call assert_close(fit%sse, 104.837152283412_dp, "multiplicative SSE", allowed_error=tolerance)
   call assert_close(fit%final_level, 21.7750587562138_dp, "multiplicative final level", &
      allowed_error=tolerance)
   call assert_close(fit%final_trend, 0.720374471659253_dp, "multiplicative final trend", &
      allowed_error=tolerance)
   call assert_vector_close(fit%final_season, &
      [0.895426940144123_dp, 1.06208052580598_dp, 1.03874770531048_dp, &
       1.04808695242701_dp], "multiplicative final season", allowed_error=tolerance)
   call assert_vector_close(predict_holt_winters(fit, 6), &
      [20.1430169424508_dp, 24.6570572485298_dp, 24.863654304219_dp, &
       25.8422153091495_dp, 22.723187778114_dp, 27.7174400390781_dp], &
      "multiplicative forecasts", allowed_error=tolerance)
   prediction = predict_holt_winters_interval(fit, 6, 0.9_dp)
   call assert_integer(prediction%status, 0, "multiplicative interval status")
   call assert_vector_approx(prediction%upper, &
      [23.0835346778737_dp, 28.7775244013813_dp, 29.879511445281_dp, &
       32.6690586028438_dp, 29.940492184143_dp, 37.1762513174071_dp], &
      2.0e-9_dp, "multiplicative upper intervals")
   call assert_vector_approx(prediction%lower, &
      [17.202499207028_dp, 20.5365900956784_dp, 19.8477971631571_dp, &
       19.0153720154551_dp, 15.505883372085_dp, 18.2586287607491_dp], &
      2.0e-9_dp, "multiplicative lower intervals")

   fit = holt_winters_auto(x, 4, 0.4_dp, 0.2_dp, 0.3_dp)
   call assert_integer(fit%status, 0, "automatic additive status")
   call assert_close(fit%initial_level, 14.375_dp, "automatic initial level", &
      allowed_error=tolerance)
   call assert_close(fit%initial_trend, 0.4625_dp, "automatic initial trend", &
      allowed_error=tolerance)
   call assert_vector_close(fit%initial_season, &
      [-2.71875_dp, 0.78125_dp, -0.84375_dp, 2.78125_dp], &
      "automatic additive initial season", allowed_error=tolerance)
   call assert_close(fit%sse, 1.34194076732151_dp, "automatic additive SSE", &
      allowed_error=tolerance)
   call assert_vector_close(predict_holt_winters(fit, 6), &
      [19.1431077509002_dp, 23.1332738596238_dp, 22.0580359714793_dp, &
       26.1040970525906_dp, 21.226661097135_dp, 25.2168272058586_dp], &
      "automatic additive forecasts", allowed_error=tolerance)

   fit = holt_winters_auto(x, 4, 0.4_dp, 0.2_dp, 0.3_dp, multiplicative=.true.)
   call assert_integer(fit%status, 0, "automatic multiplicative status")
   call assert_vector_close(fit%initial_season, &
      [0.826832410898243_dp, 1.04797338706748_dp, 0.942813427811571_dp, &
       1.18238077422271_dp], "automatic multiplicative initial season", allowed_error=tolerance)
   call assert_close(fit%sse, 4.10977909307658_dp, "automatic multiplicative SSE", &
      allowed_error=tolerance)

   fit = holt_winters_auto(x, 4, 0.4_dp, 0.0_dp, 0.3_dp, use_trend=.false.)
   call assert_integer(fit%status, 0, "automatic seasonal no-trend status")
   call assert_close(fit%sse, 17.2010237494358_dp, "automatic seasonal no-trend SSE", &
      allowed_error=tolerance)
   call assert_vector_close(predict_holt_winters(fit, 4), &
      [17.971799698256_dp, 21.500520704176_dp, 19.949381682128_dp, &
       23.5111117015392_dp], "automatic seasonal no-trend forecasts", allowed_error=tolerance)

   fit = holt_winters_optimize(x, 4)
   call assert_integer(fit%status, 0, "optimized additive status")
   if (.not. fit%optimized) error stop "optimized additive flag"
   call assert_approx(fit%alpha, 0.968784442514194_dp, 2.0e-4_dp, &
                      "optimized additive alpha")
   call assert_approx(fit%beta, 0.0405915358081265_dp, 2.0e-4_dp, &
                      "optimized additive beta")
   call assert_approx(fit%gamma, 1.0_dp, 2.0e-4_dp, "optimized additive gamma")
   call assert_approx(fit%sse, 0.868420590460287_dp, 2.0e-6_dp, &
                      "optimized additive SSE")

   fit = holt_winters_optimize(x, 4, multiplicative=.true.)
   call assert_integer(fit%status, 0, "optimized multiplicative status")
   call assert_approx(fit%alpha, 0.414424736751695_dp, 2.0e-4_dp, &
                      "optimized multiplicative alpha")
   call assert_approx(fit%beta, 0.0_dp, 2.0e-4_dp, "optimized multiplicative beta")
   call assert_approx(fit%gamma, 1.0_dp, 2.0e-4_dp, "optimized multiplicative gamma")
   call assert_approx(fit%sse, 1.92090637805363_dp, 2.0e-6_dp, &
                      "optimized multiplicative SSE")

   y = [8.0_dp, 11.0_dp, 10.0_dp, 9.0_dp, 12.0_dp, 11.0_dp, &
        10.0_dp, 13.0_dp, 12.0_dp, 11.0_dp, 14.0_dp, 13.0_dp]
   fit = holt_winters_auto(y, 3, 0.35_dp, 0.15_dp, 0.25_dp)
   call assert_integer(fit%status, 0, "odd-period initialization status")
   call assert_close(fit%sse, 0.700180436143704_dp, "odd-period additive SSE", &
      allowed_error=tolerance)
   call assert_vector_close(predict_holt_winters(fit, 4), &
      [12.1451562948591_dp, 15.1486602935385_dp, 14.1590479275487_dp, &
       13.2633147651619_dp], "odd-period additive forecasts", allowed_error=tolerance)

   z = [10.0_dp, 12.0_dp, 11.0_dp, 14.0_dp, 13.0_dp, 15.0_dp, 16.0_dp, 15.0_dp]
   fit = holt_winters_reduced(z, 0.4_dp, initial_level=10.0_dp, beta=0.2_dp, &
                              initial_trend=0.5_dp)
   call assert_integer(fit%status, 0, "Holt trend status")
   if (.not. fit%has_trend .or. fit%has_season) error stop "Holt trend components"
   call assert_vector_close(fit%fitted, &
      [10.5_dp, 11.24_dp, 13.1048_dp, 13.815296_dp, 15.13636992_dp, &
       16.3981046784_dp], "Holt trend fitted values", allowed_error=tolerance)
   call assert_close(fit%sse, 11.9826602144608_dp, "Holt trend SSE", allowed_error=tolerance)
   call assert_vector_close(predict_holt_winters(fit, 4), &
      [16.643297159168_dp, 17.447731511296_dp, 18.252165863424_dp, &
       19.056600215552_dp], "Holt trend forecasts", allowed_error=tolerance)
   prediction = predict_holt_winters_interval(fit, 4, 0.9_dp)
   call assert_vector_approx(prediction%upper, &
      [18.9188035507227_dp, 19.9718004995534_dp, 21.0796599656073_dp, &
       22.2371037534731_dp], 2.0e-9_dp, "Holt trend upper intervals")
   call assert_vector_approx(prediction%lower, &
      [14.3677907676133_dp, 14.9236625230386_dp, 15.4246717612407_dp, &
       15.8760966776309_dp], 2.0e-9_dp, "Holt trend lower intervals")

   fit = holt_winters_reduced(z, 0.4_dp, beta=0.2_dp)
   call assert_close(fit%sse, 30.4211638177834_dp, "default Holt trend SSE", &
      allowed_error=tolerance)
   call assert_close(fit%final_level, 16.77836722176_dp, "default Holt final level", &
      allowed_error=tolerance)
   call assert_close(fit%final_trend, 1.037998252032_dp, "default Holt final trend", &
      allowed_error=tolerance)

   fit = holt_winters_reduced(z, 0.4_dp, initial_level=10.0_dp)
   call assert_integer(fit%status, 0, "simple smoothing status")
   if (fit%has_trend .or. fit%has_season) error stop "simple smoothing components"
   call assert_vector_close(fit%fitted, &
      [10.0_dp, 10.8_dp, 10.88_dp, 12.128_dp, 12.4768_dp, &
       13.48608_dp, 14.491648_dp], "simple smoothing fitted values", allowed_error=tolerance)
   call assert_close(fit%sse, 27.479537762304_dp, "simple smoothing SSE", allowed_error=tolerance)
   call assert_vector_close(predict_holt_winters(fit, 4), &
      [14.6949888_dp, 14.6949888_dp, 14.6949888_dp, 14.6949888_dp], &
      "simple smoothing forecasts", allowed_error=tolerance)
   prediction = predict_holt_winters_interval(fit, 4, 0.9_dp)
   call assert_vector_approx(prediction%upper, &
      [16.5702132339939_dp, 16.7146673254845_dp, 16.8494576474793_dp, &
       16.9762977845995_dp], 2.0e-9_dp, "simple smoothing upper intervals")
   call assert_vector_approx(prediction%lower, &
      [12.8197643660061_dp, 12.6753102745155_dp, 12.5405199525207_dp, &
       12.4136798154005_dp], 2.0e-9_dp, "simple smoothing lower intervals")

   fit = holt_winters(x(:12), 4, 0.4_dp, 0.0_dp, 0.3_dp, 10.0_dp, 0.0_dp, &
                      [-1.0_dp, 0.5_dp, 1.0_dp, -0.5_dp], use_trend=.false.)
   call assert_integer(fit%status, 0, "seasonal no-trend status")
   if (fit%has_trend .or. .not. fit%has_season) error stop "seasonal no-trend components"
   call assert_vector_close(fit%fitted, &
      [9.0_dp, 12.1_dp, 14.56_dp, 13.636_dp, 16.4016_dp, 17.50296_dp, &
       17.978976_dp, 17.3737056_dp], "seasonal no-trend fitted values", allowed_error=tolerance)
   call assert_close(fit%sse, 108.192749205647_dp, "seasonal no-trend SSE", allowed_error=tolerance)
   call assert_vector_close(predict_holt_winters(fit, 6), &
      [18.04641536_dp, 20.23017056_dp, 19.84168768_dp, 20.056956352_dp, &
       18.04641536_dp, 20.23017056_dp], "seasonal no-trend forecasts", allowed_error=tolerance)

   fit = holt_winters(x, 4, -0.1_dp, 0.2_dp, 0.3_dp, 10.0_dp, 0.5_dp, &
                      [-1.0_dp, 0.5_dp, 1.0_dp, -0.5_dp])
   call assert_integer(fit%status, 2, "invalid smoothing parameter")

   print *, "test_holt_winters: PASS"

end program test_holt_winters
