program test_time_series
   use stats_test_assertions, only: assert_integer, assert_vector_close
   use, intrinsic :: ieee_arithmetic, only: ieee_is_nan
   use r_stats, only: acf, acf_result_t, arima_sim, arma_acf, ccf, dp, filter, pacf
   implicit none

   real(dp), parameter :: tolerance = 2.0e-12_dp
   real(dp) :: innovations(8), x(8), y(8)
   real(dp), allocatable :: filtered(:), values(:)
   type(acf_result_t) :: fit

   x = [2.0_dp, 1.0_dp, 4.0_dp, 3.0_dp, 7.0_dp, 5.0_dp, 8.0_dp, 6.0_dp]
   y = [1.0_dp, 3.0_dp, 2.0_dp, 5.0_dp, 4.0_dp, 8.0_dp, 6.0_dp, 7.0_dp]

   ! Reference values generated by R 4.6.0 stats functions.
   filtered = filter(x, [0.2_dp, 0.3_dp, 0.5_dp], sides=2)
   if (.not. ieee_is_nan(filtered(1)) .or. .not. ieee_is_nan(filtered(8))) then
      error stop "centered filter boundaries"
   end if
   call assert_vector_close(filtered(2:7), &
      [2.1_dp, 2.3_dp, 4.3_dp, 4.6_dp, 6.6_dp, 6.1_dp], "centered convolution filter", &
      allowed_error=tolerance)

   filtered = filter(x, [0.2_dp, 0.3_dp, 0.5_dp], sides=1)
   if (any(.not. ieee_is_nan(filtered(1:2)))) error stop "one-sided filter boundaries"
   call assert_vector_close(filtered(3:8), &
      [2.1_dp, 2.3_dp, 4.3_dp, 4.6_dp, 6.6_dp, 6.1_dp], "one-sided convolution filter", &
      allowed_error=tolerance)

   filtered = filter(x, [0.5_dp, -0.2_dp], method="recursive")
   call assert_vector_close(filtered, &
      [2.0_dp, 2.0_dp, 4.6_dp, 4.9_dp, 8.53_dp, 8.285_dp, 10.4365_dp, 9.56125_dp], &
      "recursive filter with zero state", allowed_error=tolerance)
   filtered = filter(x, [0.5_dp, -0.2_dp], method="recursive", initial=[10.0_dp, 20.0_dp])
   call assert_vector_close(filtered, &
      [3.0_dp, 0.5_dp, 3.65_dp, 4.725_dp, 8.6325_dp, 8.37125_dp, 10.459125_dp, 9.5553125_dp], &
      "recursive filter with explicit state", allowed_error=tolerance)

   fit = acf(x, lag_max=4)
   call assert_integer(fit%status, 0, "ACF status")
   call assert_vector_close(fit%lag, [0.0_dp, 1.0_dp, 2.0_dp, 3.0_dp, 4.0_dp], "ACF lags", &
      allowed_error=tolerance)
   call assert_vector_close(fit%value, &
      [1.0_dp, 0.375_dp, 0.33333333333333331_dp, -0.16071428571428573_dp, &
       -0.28571428571428570_dp], "autocorrelation", allowed_error=tolerance)

   fit = acf(x, lag_max=4, acf_type="covariance")
   if (.not. fit%covariance) error stop "autocovariance result type"
   call assert_vector_close(fit%value, &
      [5.25_dp, 1.96875_dp, 1.75_dp, -0.84375_dp, -1.5_dp], "autocovariance", &
      allowed_error=tolerance)

   fit = pacf(x, lag_max=4)
   call assert_integer(fit%status, 0, "PACF status")
   call assert_vector_close(fit%lag, [1.0_dp, 2.0_dp, 3.0_dp, 4.0_dp], "PACF lags", &
      allowed_error=tolerance)
   call assert_vector_close(fit%value, &
      [0.375_dp, 0.22424242424242422_dp, -0.41875884016973125_dp, &
       -0.27069585136962909_dp], "partial autocorrelation", allowed_error=tolerance)

   fit = ccf(x, y, lag_max=3)
   call assert_integer(fit%status, 0, "CCF status")
   call assert_vector_close(fit%lag, &
      [-3.0_dp, -2.0_dp, -1.0_dp, 0.0_dp, 1.0_dp, 2.0_dp, 3.0_dp], "CCF lags", &
      allowed_error=tolerance)
   call assert_vector_close(fit%value, &
      [0.065476190476190479_dp, 0.107142857142857137_dp, 0.744047619047619069_dp, &
       0.571428571428571397_dp, 0.767857142857142905_dp, 0.035714285714285712_dp, &
       0.029761904761904760_dp], "cross-correlation", allowed_error=tolerance)

   fit = ccf(x, y, lag_max=3, acf_type="covariance")
   call assert_vector_close(fit%value, &
      [0.34375_dp, 0.5625_dp, 3.90625_dp, 3.0_dp, 4.03125_dp, 0.1875_dp, 0.15625_dp], &
      "cross-covariance", allowed_error=tolerance)

   values = arma_acf(ar=[0.6_dp, -0.2_dp], ma=[0.4_dp], lag_max=6)
   call assert_vector_close(values, &
      [1.0_dp, 0.65384615384615397_dp, 0.19230769230769232_dp, &
       -0.015384615384615413_dp, -0.047692307692307714_dp, &
       -0.025538461538461545_dp, -0.0057846153846153811_dp], "ARMA autocorrelation", &
      allowed_error=tolerance)
   values = arma_acf(ma=[0.5_dp, -0.25_dp], lag_max=5)
   call assert_vector_close(values, &
      [1.0_dp, 0.28571428571428570_dp, -0.19047619047619047_dp, &
       0.0_dp, 0.0_dp, 0.0_dp], "MA autocorrelation", allowed_error=tolerance)

   innovations = [1.0_dp, -0.5_dp, 0.25_dp, 0.0_dp, 0.75_dp, -1.0_dp, 0.5_dp, 0.2_dp]
   values = arima_sim(innovations, ar=[0.6_dp, -0.2_dp], ma=[0.4_dp], &
                      start_innovations=[0.1_dp, -0.2_dp, 0.3_dp])
   call assert_vector_close(values, &
      [1.2264000000000002_dp, 0.61104000000000003_dp, 0.17134399999999994_dp, &
       0.080598399999999959_dp, 0.76409024000000003_dp, -0.25766553599999992_dp, &
       -0.20741736959999998_dp, 0.32708268544000002_dp], "deterministic ARMA simulation", &
      allowed_error=tolerance)
   values = arima_sim(innovations, ar=[0.6_dp, -0.2_dp], ma=[0.4_dp], &
                      start_innovations=[0.1_dp, -0.2_dp, 0.3_dp], difference_order=1)
   call assert_vector_close(values, &
      [0.0_dp, 1.2264_dp, 1.83744_dp, 2.008784_dp, 2.0893824_dp, 2.85347264_dp, &
       2.595807104_dp, 2.3883897344_dp, 2.71547241984_dp], &
      "deterministic ARIMA integration", allowed_error=tolerance)
   values = arima_sim(innovations, ar=[0.6_dp, -0.2_dp], ma=[0.4_dp], &
                      start_innovations=[0.1_dp, -0.2_dp, 0.3_dp], difference_order=2)
   call assert_vector_close(values, &
      [0.0_dp, 0.0_dp, 1.2264_dp, 3.06384_dp, 5.072624_dp, 7.1620064_dp, &
       10.01547904_dp, 12.611286144_dp, 14.9996758784_dp, 17.71514829824_dp], &
      "deterministic ARIMA double integration", allowed_error=tolerance)
   values = arima_sim(innovations, difference_order=-1)
   call assert_integer(size(values), 0, "invalid ARIMA difference order")

   print *, "test_time_series: PASS"

end program test_time_series
