program test_t_tests
   use stats_test_assertions, only: assert_close
   use r_stats, only: dp, t_test, t_test_p_value, t_test_result_t
   implicit none

   real(dp), parameter :: tolerance = 2.0e-10_dp
   real(dp), parameter :: x_one(5) = [2.1_dp, 2.5_dp, 2.3_dp, 2.8_dp, 3.0_dp]
   real(dp), parameter :: x_two(5) = [1.2_dp, 2.4_dp, 3.1_dp, 4.8_dp, 5.0_dp]
   real(dp), parameter :: y_two(4) = [0.7_dp, 1.5_dp, 2.0_dp, 2.1_dp]
   real(dp), parameter :: x_paired(5) = [5.1_dp, 6.2_dp, 7.0_dp, 8.4_dp, 9.1_dp]
   real(dp), parameter :: y_paired(5) = [4.8_dp, 6.0_dp, 6.5_dp, 8.0_dp, 8.8_dp]
   type(t_test_result_t) :: result

   ! Reference values generated by R 4.6.0 stats::t.test.
   result = t_test(x_one, 2.0_dp)
   call assert_result(result, 3.3109524332188158_dp, 4.0_dp, 0.029628030883234176_dp, &
                      2.54_dp, 0.0_dp, 2.0871755070340137_dp, 2.992824492965986_dp, &
                      0.16309506430300089_dp, 1, "one-sample")
   call assert_close(t_test_p_value(x_one, 2.0_dp), result%p_value, "one-sample p-value adapter", &
      allowed_error=tolerance)

   result = t_test(x_two, y_two)
   call assert_result(result, 2.1867146110296125_dp, 5.4474408035016317_dp, &
                      0.075970759871066218_dp, 3.3_dp, 1.575_dp, &
                      -0.25372738281547125_dp, 3.7037273828154706_dp, &
                      0.78885465496925777_dp, 2, "Welch")
   call assert_close(t_test_p_value(x_two, y_two), result%p_value, "Welch p-value adapter", &
      allowed_error=tolerance)

   result = t_test(x_two, y_two, var_equal=.true.)
   call assert_result(result, 1.99521034736981_dp, 7.0_dp, 0.086226232395345326_dp, &
                      3.3_dp, 1.575_dp, -0.31938436246818336_dp, 3.7693843624681831_dp, &
                      0.86457049617549575_dp, 3, "equal-variance")

   result = t_test(x_paired, y_paired, paired=.true.)
   call assert_result(result, 6.667948594698248_dp, 4.0_dp, 0.002628545107680767_dp, &
                      0.33999999999999986_dp, 0.0_dp, 0.19842852230177252_dp, &
                      0.48157147769822717_dp, 0.050990195135927896_dp, 4, "paired")

   print *, "test_t_tests: PASS"

contains

   subroutine assert_result(actual, statistic, parameter, p_value, estimate, estimate2, &
                            conf_low, conf_high, stderr, method, label)
      !! Checks every numeric and method field returned by a t test.
      type(t_test_result_t), intent(in) :: actual !! Computed t-test result.
      real(dp), intent(in) :: statistic !! Expected t statistic.
      real(dp), intent(in) :: parameter !! Expected degrees of freedom.
      real(dp), intent(in) :: p_value !! Expected two-sided p-value.
      real(dp), intent(in) :: estimate !! Expected sample mean or first sample mean.
      real(dp), intent(in) :: estimate2 !! Expected second sample mean, or zero when unused.
      real(dp), intent(in) :: conf_low !! Expected lower confidence limit.
      real(dp), intent(in) :: conf_high !! Expected upper confidence limit.
      real(dp), intent(in) :: stderr !! Expected standard error.
      integer, intent(in) :: method !! Expected method identifier.
      character(len=*), intent(in) :: label !! Case description used in failure messages.

      call assert_close(actual%statistic, statistic, label//" statistic", allowed_error=tolerance)
      call assert_close(actual%parameter, parameter, label//" degrees of freedom", &
      allowed_error=tolerance)
      call assert_close(actual%p_value, p_value, label//" p-value", allowed_error=tolerance)
      call assert_close(actual%estimate, estimate, label//" estimate", allowed_error=tolerance)
      call assert_close(actual%estimate2, estimate2, label//" second estimate", &
      allowed_error=tolerance)
      call assert_close(actual%conf_low, conf_low, label//" lower confidence limit", &
      allowed_error=tolerance)
      call assert_close(actual%conf_high, conf_high, label//" upper confidence limit", &
      allowed_error=tolerance)
      call assert_close(actual%stderr, stderr, label//" standard error", allowed_error=tolerance)
      if (actual%method /= method) error stop label//" method"
   end subroutine assert_result

end program test_t_tests
