name = "cmaes-fortran"
version = "0.1.0"
license = "GPL-2.0-only"
author = "Fortran translation of cmaes by Heike Trautmann, Olaf Mersmann, and David Arnu"
copyright = "Original cmaes authors; Fortran translation"
categories = ["optimization", "statistics", "numerical"]
keywords = ["covariance", "linear-algebra", "matrix-computations", "optimization", "statistics", "numerical", "statistical-computing"]

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[dependencies]
rfortran-linalg = { path = "../rfortran-linalg" }

[library]
source-dir = "src"

[extra.r-fpm-index]
gams = ["D", "G", "L"]
