name = "poibin-fortran"
version = "0.1.0"
license = "GPL-2.0-only"
author = "Yili Hong; Fortran translation"
maintainer = "Fortran translation"
description = "Modern Fortran translation of the computational code in the R package poibin"
categories = ["statistics", "probability"]
keywords = ["poisson-binomial", "distribution", "fortran"]

[build]
auto-executables = false
auto-examples = true
auto-tests = true
module-naming = false

[library]
source-dir = "src"

[extra.r-fpm-index]
gams = ["L"]
