name = "rmoo-fortran"
version = "0.1.0"
license = "GPL-2.0-or-later"
author = "Francisco Benitez; Diego P. Pinto-Roa; Fortran translation"
maintainer = "Fortran translation"
description = "Modern Fortran translation of computational algorithms from the R rmoo package"
categories = ["optimization", "multiobjective", "genetic-algorithm"]
keywords = ["multiobjective-optimization", "optimization", "multiobjective", "genetic-algorithm", "numerical-methods"]

[build]
auto-executables = false
auto-examples = true
auto-tests = true
module-naming = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[extra.r-fpm-index]
gams = ["G"]
