! Part of the experimental modern Fortran port of timsac 1.3.8-6.
! This file was created or modified for the Fortran project on 2026-07-23.
! Original TIMSAC credits are retained; see NOTICE and ORIGIN.md.
! SPDX-License-Identifier: GPL-2.0-or-later

subroutine auspecf(n,lagh1,cxx1,p1,p2,q)
  use timsac_kinds, only: dp
  implicit none
!
!     PROGRAM 5.2.1   POWER SPECTRUM
!-----------------------------------------------------------------------
!     ** DESIGNED BY H. AKAIKE, THE INSTITUTE OF STATISTICAL MATHEMATICS
!     ** PROGRAMMED BY E. ARAHATA, THE INSTITUTE OF STATISTICAL MATHEMAT
!        TOKYO
!     ** DATE OF THE LATEST REVISION: MARCH 25, 1977
!     ** THIS PROGRAM WAS ORIGINALLY PUBLISHED IN
!        "DAINAMIKKU SISTEMU NO TOKEI-TEKI KAISEKI TO SEIGYO (STATISTICA
!        ANALYSIS AND CONTROL OF DYNAMIC SYSTEMS)" BY H. AKAIKE AND
!        T. NAKAGAWA, SAIENSU-SHA, TOKYO, 1972 (IN JAPANESE)
!-----------------------------------------------------------------------
!     THIS PROGRAM COMPUTES POWER SPECTRUM ESTIMATES FOR TWO
!     TRIGONOMETRIC WINDOWS OF BLACKMAN-TUKEY TYPE BY GOERTZEL METHOD.
!     ONLY ONE CARD OF LAGH(MAXIMUM LAG OF COVARIANCES TO BE USED FOR
!     POWER SPECTRUM COMPUTATION) SHOULD BE ADDED ON TOP OF THE OUTPUT
!     OF PROGRAM 5.1.1 AUTCOR TO FORM INPUT TO THIS PROGRAM.
!     OUTPUTS ARE ESTIMATES P1(I),P2(I) FOR FREQUENCIES I/(2LAGH*DELTAT)
!     AND THE TEST STATISTICS Q(I) FOR THE DIFFERENCES BETWEEN P1(I) AND
!     P2(I).   Q(I) GREATER THAN 1 MEANS SIGNIFICANT DIFFERENCE.
!
!      USE DFLIB
!
!xx      IMPLICIT REAL*8(A-H,O-Z)
!      DIMENSION CXX(1001),FC(1001),P1(1001),P2(1001),Q(1001)
!      DIMENSION A1(10),A2(10)
!xx      DIMENSION CXX1(LAGH1),CXX(LAGH1)
!xx      DIMENSION FC(LAGH1),P1(LAGH1),P2(LAGH1),Q(LAGH1)
!xx      DIMENSION A1(2),A2(3)
integer n, lagh1
real(dp) cxx1(lagh1), p1(lagh1), p2(lagh1), q(lagh1)
! local
integer i, mla1, mla2
real(dp) cxx(lagh1), fc(lagh1), a1(2), a2(3)
!
!     INPUT / OUTPUT DATA FILE OPEN
!	CHARACTER(100) DFNAM
!	DFNAM='auspec.out'
!	CALL SETWND
!	CALL FLOPN3(DFNAM,NFL)
!	IF (NFL.EQ.0) GO TO 999
!
!     WINDOW W1 DEFINITION
mla1=2
a1(1)=0.5d-00
a1(2)=0.25d-00
!     WINDOW W2 DEFINITION
mla2=3
a2(1)=0.625d-00
a2(2)=0.25d-00
a2(3)=-0.0625d-00
!
!     LAGH SPECIFICATION
!      READ(5,1) LAGH
!      LAGH1=LAGH+1
!     READING THE OUTPUTS OF PROGRAM 5.1.1 AUTCOR
!      READ(5,1) N,LAGH0
!      LAGH3=LAGH0+1
!     INITIAL CONDITION PRINT OUT
!      WRITE(6,60)
!      WRITE(6,61)
!      WRITE(6,62) N,LAGH
!      WRITE(6,63)
!      CALL PRCOL1(A1,1,MLA1,1)
!      WRITE(6,64)
!      CALL PRCOL1(A2,1,MLA2,1)
!     AUTO COVARIANCE INPUT
!      READ(5,2) (CXX(I),I=1,LAGH3)
!     AUTO COVARIANCE PRINT OUT
!      WRITE(6,172)
!      WRITE(6,162)
!      CALL PRCOL1(CXX,1,LAGH1,1)
!      DO 10 I=2,LAGH
!   10 CXX(I)=CXX(I)+CXX(I)
cxx(1)=cxx1(1)
do 10 i=2,lagh1-1
!xx   10 CXX(I)=CXX1(I)+CXX1(I)
cxx(i)=cxx1(i)+cxx1(i)
10 continue
cxx(lagh1)=cxx1(lagh1)
!     F-COS TRANSFORMATION
call fgerco(cxx,lagh1,fc,lagh1)
!     SPECTRUM SMOOTHING BY WINDOW W1
call ausp(fc,p1,lagh1,a1,mla1)
!     SPECTRUM SMOOTHING BY WINDOW W2
call ausp(fc,p2,lagh1,a2,mla2)
!     TEST STATISTICS COMPUTATION
call signif(p1,p2,q,lagh1,n)
!     AUTO SPECTRUM AND TEST STATISTICS PRINT OUT
!      WRITE(6,66) N,LAGH
!      WRITE(6,67)
!      CALL PRCOL3(P1,P2,Q,1,LAGH1,1)
!     AUTO SPECTRUM SMOOTHED BY WINDOW W1 PUNCH OUT
!      WRITE(7,1) N,LAGH
!      WRITE(7,2) (P1(I),I=1,LAGH1)
!	CALL FLCLS3(NFL)
!    1 FORMAT(10I5)
!    2 FORMAT(4D20.10)
!   60 FORMAT(1H ,30HPROGRAM 5.2.1   POWER SPECTRUM)
!   62 FORMAT(1H ,2HN=,I5,5X,5HLAGH=,I5)
!   61 FORMAT(1H ,17HINITIAL CONDITION)
!   63 FORMAT(1H ,12X,9HWINDOW W1/1H ,4X,1HI,11X,5HA1(I))
!   64 FORMAT(1H ,12X,9HWINDOW W2/1H ,4X,1HI,11X,5HA2(I))
!   66 FORMAT(//1H ,14HPOWER SPECTRUM,5X,2HN=,I5,5X,5HLAGH=,I5)
!   67 FORMAT(1H ,4X,1HI,8X,8HPOWER W1,6X,8HPOWER W2,2X,12HSIGNIFICANCE)
!  162 FORMAT(1H ,4X,1HI,6X,6HCXX(I))
!  172 FORMAT(1H ,5X,15HAUTO COVARIANCE)
return
end subroutine
