name = "splines-fortran"
version = "0.1.0"
license = "GPL-2.0-or-later"
author = "Fortran translation of Douglas M. Bates and William N. Venables' splines package"
maintainer = ""
copyright = "1998 Douglas M. Bates and William N. Venables; Fortran translation 2026"
description = "Modern Fortran translation of the computational routines in the R splines package"
categories = ["numerical"]
keywords = ["smoothing", "numerical", "numerical-methods"]

[build]
auto-executables = true
auto-examples = true
auto-tests = true
module-naming = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
