name = "sharper"
version = "1.4.0"
license = "LGPL-3.0-or-later"
author = "Steven E. Pav; modern Fortran translation"
maintainer = ""
copyright = "Copyright 2012-2025 Steven E. Pav"
description = "Modern Fortran translation of the computational core of SharpeR"
categories = ["finance", "statistics"]
gams = ["L"]
keywords = ["Sharpe ratio", "Hotelling T2", "Markowitz", "inference"]

[build]
auto-executables = true
auto-examples = true
auto-tests = true
module-naming = false

[install]
library = true
