name = "derivmkts"
version = "0.2.5"
license = "MIT"
author = "Robert L. McDonald; modern Fortran translation"
maintainer = ""
copyright = "2014-2022 Robert L. McDonald"
description = "Modern Fortran translation of the numerical routines in the R derivmkts package"
categories = ["finance", "numerical"]
gams = ["H", "L"]
keywords = ["numerical-differentiation", "finance", "numerical", "numerical-methods"]

[library]
source-dir = "src"

[build]
auto-executables = true
auto-examples = true
auto-tests = true
module-naming = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
