name = "joker-fortran"
version = "0.2.0"
license = "GPL-3.0-or-later"
author = "Fortran translation of joker"
maintainer = ""
copyright = ""
categories = ["probability", "statistics"]
keywords = ["estimation", "probability-distributions", "probability", "statistics", "statistical-computing"]

[build]
auto-executables = true
auto-tests = true
auto-examples = true
