name = "limsolve-fortran"
version = "0.1.0"
license = "GPL"
author = "Fortran translation of limSolve"
maintainer = ""
description = "Modern Fortran/FPM translation of the computational core of R package limSolve"
categories = ["optimization", "statistics", "numerical"]
keywords = ["constrained-optimization", "optimization", "statistics", "numerical", "statistical-computing"]

[library]
source-dir = "src"

[dependencies]
lpsolve-fortran = { path = "../lpSolve" }
quadprog-fortran = { path = "../quadprog" }

[build]
auto-executables = false
auto-examples = true
auto-tests = true

[extra.r-fpm-index]
gams = ["G", "L"]
