# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.chf <- function(k, d1) {
    .Call(`_rvMF_chf`, k, d1)
}

.rvMF64 <- function(n, p, kappa, log_const) {
    .Call(`_rvMF_rvMF64`, n, p, kappa, log_const)
}

