name = "compound-Cox-fortran"
version = "0.1.0"
license = "GPL-2.0-only"
author = "Takeshi Emura et al.; Fortran translation"
description = "Modern Fortran translation of the numerical core of R package compound.Cox"
[build]
auto-executables = true
auto-examples = true
auto-tests = true
module-naming = false
[library]
source-dir = "src"
[dependencies]
numDeriv-fortran = { path = "vendor/numDeriv-fortran" }
survival-fortran-core = { path = "vendor/survival-fortran" }

[extra.r-fpm-index]
gams = ["Z"]
