// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// gl_sim_stats
Rcpp::List gl_sim_stats(const arma::mat& XX, const arma::mat& Xtemp_XX, const arma::mat& XXB0, const arma::mat& Ehat0, const arma::mat& H, const arma::mat& C, const arma::mat& premult, const arma::mat& sign_mat, const arma::rowvec& ssrr_bmc);
RcppExport SEXP _spantest_gl_sim_stats(SEXP XXSEXP, SEXP Xtemp_XXSEXP, SEXP XXB0SEXP, SEXP Ehat0SEXP, SEXP HSEXP, SEXP CSEXP, SEXP premultSEXP, SEXP sign_matSEXP, SEXP ssrr_bmcSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type XX(XXSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Xtemp_XX(Xtemp_XXSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type XXB0(XXB0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Ehat0(Ehat0SEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type H(HSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type C(CSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type premult(premultSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type sign_mat(sign_matSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec& >::type ssrr_bmc(ssrr_bmcSEXP);
    rcpp_result_gen = Rcpp::wrap(gl_sim_stats(XX, Xtemp_XX, XXB0, Ehat0, H, C, premult, sign_mat, ssrr_bmc));
    return rcpp_result_gen;
END_RCPP
}
// garch_filter
NumericVector garch_filter(NumericVector z, double omega, double alpha, double beta);
RcppExport SEXP _spantest_garch_filter(SEXP zSEXP, SEXP omegaSEXP, SEXP alphaSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< double >::type omega(omegaSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(garch_filter(z, omega, alpha, beta));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_spantest_gl_sim_stats", (DL_FUNC) &_spantest_gl_sim_stats, 9},
    {"_spantest_garch_filter", (DL_FUNC) &_spantest_garch_filter, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_spantest(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
