name = "qrmtools"
version = "0.0.19"
license = "GPL-3.0-or-later"
author = "Marius Hofert, Kurt Hornik, Alexander J. McNeil; Fortran translation"
maintainer = "Fortran translation contributors"
copyright = "Copyright (C) 2016 Marius Hofert, Kurt Hornik and Alexander J. McNeil"
description = "Modern Fortran numerical translation of qrmtools"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
