name = "chyper-fortran"
version = "0.1.1"
license = "MIT"
author = "William Nickols; Fortran translation"
maintainer = "Fortran translation"
description = "Modern Fortran implementation of conditional hypergeometric distributions"
categories = ["probability", "numerical", "statistics"]
gams = ["C", "L"]
keywords = ["probability-distributions", "hypergeometric-distribution", "probability", "numerical", "statistics", "statistical-computing"]

[build]
auto-executables = true
auto-tests = true
auto-examples = true

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
