name = "gamlss-dist-fortran"
version = "0.3.0"
license = "GPL-3.0-only"
author = "Fortran translation of the gamlss.dist package"
maintainer = ""
copyright = "gamlss.dist authors; Fortran translation 2026"
description = "Modern Fortran computational translation of the R gamlss.dist package"
categories = ["probability", "statistics", "numerical"]
keywords = ["probability-distributions", "probability", "statistics", "numerical", "statistical-computing"]

[build]
auto-executables = false
auto-tests = true
auto-examples = true
module-naming = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[library]
source-dir = "src"

[extra.r-fpm-index]
gams = ["L"]
