name = "compare-corpcor-market"
version = "0.1.0"

[dependencies]
corpcor = { path = "../../corpcor" }
comparison_data = { path = "../common" }

[build]
auto-executables = true
auto-examples = false
auto-tests = false
