# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rsdc_filter_full_cpp <- function(y, sigma, mode, P0, X, beta, xi_init) {
    .Call(`_RSDC_rsdc_filter_full_cpp`, y, sigma, mode, P0, X, beta, xi_init)
}

rsdc_loglik_cpp <- function(y, sigma, mode, P0, X, beta, xi_init) {
    .Call(`_RSDC_rsdc_loglik_cpp`, y, sigma, mode, P0, X, beta, xi_init)
}

