name = "tensora"
version = "0.1.0"
license = "GPL-2.0-or-later"
author = "K. Gerald van den Boogaart; Fortran translation"
maintainer = "Fortran translation"
description = "Free-format modern Fortran translation of the computational core of R tensorA"
categories = ["numerical"]
keywords = ["matrix-computations", "numerical", "numerical-methods"]

[build]
auto-executables = false
auto-tests = true
auto-examples = true
module-naming = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[extra.r-fpm-index]
gams = ["D"]
