# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gl_sim_stats <- function(XX, Xtemp_XX, XXB0, Ehat0, H, C, premult, sign_mat, ssrr_bmc) {
    .Call(`_spantest_gl_sim_stats`, XX, Xtemp_XX, XXB0, Ehat0, H, C, premult, sign_mat, ssrr_bmc)
}

garch_filter <- function(z, omega, alpha, beta) {
    .Call(`_spantest_garch_filter`, z, omega, alpha, beta)
}

